namespace GT5_Car_hack_workshop_2
{
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		
		private void InitializeComponent()
		{
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Button22 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.TabControl2 = new global::System.Windows.Forms.TabControl();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.GroupBox10 = new global::System.Windows.Forms.GroupBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.GroupBox9 = new global::System.Windows.Forms.GroupBox();
			this.TextBox23 = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.TextBox8 = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label35 = new global::System.Windows.Forms.Label();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.TextBox22 = new global::System.Windows.Forms.TextBox();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.EngineCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.TextBox20 = new global::System.Windows.Forms.TextBox();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.TextBox21 = new global::System.Windows.Forms.TextBox();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
			this.TextBox13 = new global::System.Windows.Forms.TextBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.TextBox12 = new global::System.Windows.Forms.TextBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TextBox9 = new global::System.Windows.Forms.TextBox();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.Button17 = new global::System.Windows.Forms.Button();
			this.Button16 = new global::System.Windows.Forms.Button();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.TextBox11 = new global::System.Windows.Forms.TextBox();
			this.TextBox19 = new global::System.Windows.Forms.TextBox();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox3 = new global::System.Windows.Forms.CheckBox();
			this.Button14 = new global::System.Windows.Forms.Button();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.GroupBox14 = new global::System.Windows.Forms.GroupBox();
			this.Button21 = new global::System.Windows.Forms.Button();
			this.Button20 = new global::System.Windows.Forms.Button();
			this.Label39 = new global::System.Windows.Forms.Label();
			this.GroupBox13 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox4 = new global::System.Windows.Forms.CheckBox();
			this.TextBox24 = new global::System.Windows.Forms.TextBox();
			this.Label38 = new global::System.Windows.Forms.Label();
			this.GroupBox12 = new global::System.Windows.Forms.GroupBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.TextBox10 = new global::System.Windows.Forms.TextBox();
			this.TextBox16 = new global::System.Windows.Forms.TextBox();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.GroupBox11 = new global::System.Windows.Forms.GroupBox();
			this.Button19 = new global::System.Windows.Forms.Button();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.TextBox14 = new global::System.Windows.Forms.TextBox();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.TextBox15 = new global::System.Windows.Forms.TextBox();
			this.TextBox17 = new global::System.Windows.Forms.TextBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.TextBox18 = new global::System.Windows.Forms.TextBox();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.TabControl1 = new global::System.Windows.Forms.TabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.ComboBox8 = new global::System.Windows.Forms.ComboBox();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.ComboBox7 = new global::System.Windows.Forms.ComboBox();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.ComboBox6 = new global::System.Windows.Forms.ComboBox();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.ComboBox5 = new global::System.Windows.Forms.ComboBox();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.ComboBox4 = new global::System.Windows.Forms.ComboBox();
			this.Label25 = new global::System.Windows.Forms.Label();
			this.ComboBox3 = new global::System.Windows.Forms.ComboBox();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.Button18 = new global::System.Windows.Forms.Button();
			this.Button15 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.CheckBox5 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox6 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox7 = new global::System.Windows.Forms.CheckBox();
			this.Button23 = new global::System.Windows.Forms.Button();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.TabControl2.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.GroupBox10.SuspendLayout();
			this.GroupBox9.SuspendLayout();
			this.GroupBox8.SuspendLayout();
			this.GroupBox7.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.GroupBox14.SuspendLayout();
			this.GroupBox13.SuspendLayout();
			this.GroupBox12.SuspendLayout();
			this.GroupBox11.SuspendLayout();
			this.TabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.SuspendLayout();
			this.GroupBox1.Controls.Add(this.Button22);
			this.GroupBox1.Controls.Add(this.Button5);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Controls.Add(this.TextBox2);
			this.GroupBox1.Controls.Add(this.Button3);
			this.GroupBox1.Controls.Add(this.Button2);
			this.GroupBox1.Controls.Add(this.Button1);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.TextBox1);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			global::System.Drawing.Point point = new global::System.Drawing.Point(13, 13);
			groupBox.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(368, 101);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Before and after you start hacking";
			this.Button22.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 192);
			this.Button22.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control button = this.Button22;
			point = new global::System.Drawing.Point(300, 70);
			button.Location = point;
			this.Button22.Name = "Button22";
			global::System.Windows.Forms.Control button2 = this.Button22;
			size = new global::System.Drawing.Size(62, 23);
			button2.Size = size;
			this.Button22.TabIndex = 8;
			this.Button22.Text = "About";
			this.Button22.UseVisualStyleBackColor = false;
			this.Button5.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
			global::System.Windows.Forms.Control button3 = this.Button5;
			point = new global::System.Drawing.Point(183, 70);
			button3.Location = point;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control button4 = this.Button5;
			size = new global::System.Drawing.Size(75, 23);
			button4.Size = size;
			this.Button5.TabIndex = 7;
			this.Button5.Text = "Save only";
			this.Button5.UseVisualStyleBackColor = false;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label2;
			point = new global::System.Drawing.Point(185, 20);
			label.Location = point;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label2 = this.Label2;
			size = new global::System.Drawing.Size(58, 13);
			label2.Size = size;
			this.Label2.TabIndex = 6;
			this.Label2.Text = "PSN name";
			global::System.Windows.Forms.Control textBox = this.TextBox2;
			point = new global::System.Drawing.Point(248, 17);
			textBox.Location = point;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control textBox2 = this.TextBox2;
			size = new global::System.Drawing.Size(113, 20);
			textBox2.Size = size;
			this.TextBox2.TabIndex = 5;
			this.Button3.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			global::System.Windows.Forms.Control button5 = this.Button3;
			point = new global::System.Drawing.Point(82, 70);
			button5.Location = point;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(100, 23);
			button6.Size = size;
			this.Button3.TabIndex = 4;
			this.Button3.Text = "Save and encrypt";
			this.Button3.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.Color.FromArgb(255, 192, 192);
			global::System.Windows.Forms.Control button7 = this.Button2;
			point = new global::System.Drawing.Point(6, 70);
			button7.Location = point;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button8 = this.Button2;
			size = new global::System.Drawing.Size(75, 23);
			button8.Size = size;
			this.Button2.TabIndex = 3;
			this.Button2.Text = "Load data";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button1.BackColor = global::System.Drawing.Color.FromArgb(255, 224, 192);
			global::System.Windows.Forms.Control button9 = this.Button1;
			point = new global::System.Drawing.Point(104, 15);
			button9.Location = point;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button10 = this.Button1;
			size = new global::System.Drawing.Size(75, 23);
			button10.Size = size;
			this.Button1.TabIndex = 2;
			this.Button1.Text = "Browse";
			this.Button1.UseVisualStyleBackColor = false;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label1;
			point = new global::System.Drawing.Point(6, 20);
			label3.Location = point;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label4 = this.Label1;
			size = new global::System.Drawing.Size(96, 13);
			label4.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "GT5.0 file location:";
			global::System.Windows.Forms.Control textBox3 = this.TextBox1;
			point = new global::System.Drawing.Point(6, 44);
			textBox3.Location = point;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox4 = this.TextBox1;
			size = new global::System.Drawing.Size(355, 20);
			textBox4.Size = size;
			this.TextBox1.TabIndex = 0;
			this.GroupBox2.Controls.Add(this.TabControl2);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			point = new global::System.Drawing.Point(387, 13);
			groupBox3.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(478, 446);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 1;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Basic hacks";
			this.TabControl2.Controls.Add(this.TabPage2);
			this.TabControl2.Controls.Add(this.TabPage3);
			global::System.Windows.Forms.Control tabControl = this.TabControl2;
			point = new global::System.Drawing.Point(6, 15);
			tabControl.Location = point;
			this.TabControl2.Name = "TabControl2";
			this.TabControl2.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabControl2 = this.TabControl2;
			size = new global::System.Drawing.Size(466, 425);
			tabControl2.Size = size;
			this.TabControl2.TabIndex = 1;
			this.TabPage2.Controls.Add(this.GroupBox10);
			this.TabPage2.Controls.Add(this.GroupBox9);
			this.TabPage2.Controls.Add(this.GroupBox8);
			this.TabPage2.Controls.Add(this.GroupBox7);
			this.TabPage2.Controls.Add(this.GroupBox6);
			this.TabPage2.Controls.Add(this.GroupBox5);
			this.TabPage2.Controls.Add(this.GroupBox4);
			this.TabPage2.Controls.Add(this.GroupBox3);
			this.TabPage2.Controls.Add(this.Label7);
			global::System.Windows.Forms.TabPage tabPage = this.TabPage2;
			point = new global::System.Drawing.Point(4, 22);
			tabPage.Location = point;
			this.TabPage2.Name = "TabPage2";
			global::System.Windows.Forms.Control tabPage2 = this.TabPage2;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			tabPage2.Padding = padding;
			global::System.Windows.Forms.Control tabPage3 = this.TabPage2;
			size = new global::System.Drawing.Size(458, 399);
			tabPage3.Size = size;
			this.TabPage2.TabIndex = 0;
			this.TabPage2.Text = "Page 1";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.GroupBox10.Controls.Add(this.Label4);
			this.GroupBox10.Controls.Add(this.TextBox4);
			this.GroupBox10.Controls.Add(this.TextBox5);
			this.GroupBox10.Controls.Add(this.Label5);
			this.GroupBox10.Controls.Add(this.Button8);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox10;
			point = new global::System.Drawing.Point(6, 107);
			groupBox5.Location = point;
			this.GroupBox10.Name = "GroupBox10";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox10;
			size = new global::System.Drawing.Size(221, 40);
			groupBox6.Size = size;
			this.GroupBox10.TabIndex = 45;
			this.GroupBox10.TabStop = false;
			this.GroupBox10.Text = "Torque";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label5 = this.Label4;
			point = new global::System.Drawing.Point(6, 16);
			label5.Location = point;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label6 = this.Label4;
			size = new global::System.Drawing.Size(55, 13);
			label6.Size = size;
			this.Label4.TabIndex = 3;
			this.Label4.Text = "Tq. Split";
			global::System.Windows.Forms.Control textBox5 = this.TextBox4;
			point = new global::System.Drawing.Point(67, 13);
			textBox5.Location = point;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control textBox6 = this.TextBox4;
			size = new global::System.Drawing.Size(38, 20);
			textBox6.Size = size;
			this.TextBox4.TabIndex = 4;
			global::System.Windows.Forms.Control textBox7 = this.TextBox5;
			point = new global::System.Drawing.Point(127, 13);
			textBox7.Location = point;
			this.TextBox5.Name = "TextBox5";
			this.TextBox5.ReadOnly = true;
			global::System.Windows.Forms.Control textBox8 = this.TextBox5;
			size = new global::System.Drawing.Size(38, 20);
			textBox8.Size = size;
			this.TextBox5.TabIndex = 5;
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label5;
			point = new global::System.Drawing.Point(111, 16);
			label7.Location = point;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label8 = this.Label5;
			size = new global::System.Drawing.Size(10, 13);
			label8.Size = size;
			this.Label5.TabIndex = 6;
			this.Label5.Text = ":";
			global::System.Windows.Forms.Control button11 = this.Button8;
			point = new global::System.Drawing.Point(171, 11);
			button11.Location = point;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control button12 = this.Button8;
			size = new global::System.Drawing.Size(26, 23);
			button12.Size = size;
			this.Button8.TabIndex = 14;
			this.Button8.Text = "?";
			this.Button8.UseVisualStyleBackColor = true;
			this.GroupBox9.Controls.Add(this.TextBox23);
			this.GroupBox9.Controls.Add(this.Label11);
			this.GroupBox9.Controls.Add(this.TextBox8);
			this.GroupBox9.Controls.Add(this.Label10);
			this.GroupBox9.Controls.Add(this.Label35);
			this.GroupBox9.Controls.Add(this.TextBox7);
			this.GroupBox9.Controls.Add(this.Button6);
			this.GroupBox9.Controls.Add(this.TextBox6);
			this.GroupBox9.Controls.Add(this.Label6);
			this.GroupBox9.Controls.Add(this.TextBox22);
			this.GroupBox9.Controls.Add(this.Button7);
			this.GroupBox9.Controls.Add(this.Button4);
			this.GroupBox9.Controls.Add(this.Label3);
			this.GroupBox9.Controls.Add(this.EngineCodeTextBox);
			this.GroupBox9.Controls.Add(this.TextBox20);
			this.GroupBox9.Controls.Add(this.Label33);
			this.GroupBox9.Controls.Add(this.Label32);
			this.GroupBox9.Controls.Add(this.TextBox21);
			this.GroupBox9.Controls.Add(this.Label34);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox9;
			point = new global::System.Drawing.Point(233, 7);
			groupBox7.Location = point;
			this.GroupBox9.Name = "GroupBox9";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox9;
			size = new global::System.Drawing.Size(219, 269);
			groupBox8.Size = size;
			this.GroupBox9.TabIndex = 44;
			this.GroupBox9.TabStop = false;
			this.GroupBox9.Text = "Car parts";
			global::System.Windows.Forms.Control textBox9 = this.TextBox23;
			point = new global::System.Drawing.Point(91, 87);
			textBox9.Location = point;
			this.TextBox23.Name = "TextBox23";
			global::System.Windows.Forms.Control textBox10 = this.TextBox23;
			size = new global::System.Drawing.Size(66, 20);
			textBox10.Size = size;
			this.TextBox23.TabIndex = 52;
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label9 = this.Label11;
			point = new global::System.Drawing.Point(5, 142);
			label9.Location = point;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label10 = this.Label11;
			size = new global::System.Drawing.Size(80, 13);
			label10.Size = size;
			this.Label11.TabIndex = 19;
			this.Label11.Text = "Transmission";
			global::System.Windows.Forms.Control textBox11 = this.TextBox8;
			point = new global::System.Drawing.Point(91, 139);
			textBox11.Location = point;
			this.TextBox8.Name = "TextBox8";
			global::System.Windows.Forms.Control textBox12 = this.TextBox8;
			size = new global::System.Drawing.Size(66, 20);
			textBox12.Size = size;
			this.TextBox8.TabIndex = 20;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label11 = this.Label10;
			point = new global::System.Drawing.Point(35, 168);
			label11.Location = point;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label12 = this.Label10;
			size = new global::System.Drawing.Size(50, 13);
			label12.Size = size;
			this.Label10.TabIndex = 18;
			this.Label10.Text = "Chassis";
			this.Label35.AutoSize = true;
			this.Label35.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label35.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label13 = this.Label35;
			point = new global::System.Drawing.Point(51, 90);
			label13.Location = point;
			this.Label35.Name = "Label35";
			global::System.Windows.Forms.Control label14 = this.Label35;
			size = new global::System.Drawing.Size(34, 13);
			label14.Size = size;
			this.Label35.TabIndex = 51;
			this.Label35.Text = "Horn";
			global::System.Windows.Forms.Control textBox13 = this.TextBox7;
			point = new global::System.Drawing.Point(91, 165);
			textBox13.Location = point;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control textBox14 = this.TextBox7;
			size = new global::System.Drawing.Size(66, 20);
			textBox14.Size = size;
			this.TextBox7.TabIndex = 17;
			this.Button6.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 255);
			global::System.Windows.Forms.Control button13 = this.Button6;
			point = new global::System.Drawing.Point(91, 217);
			button13.Location = point;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control button14 = this.Button6;
			size = new global::System.Drawing.Size(71, 20);
			button14.Size = size;
			this.Button6.TabIndex = 9;
			this.Button6.Text = "Make 4WD";
			this.Button6.UseVisualStyleBackColor = false;
			global::System.Windows.Forms.Control textBox15 = this.TextBox6;
			point = new global::System.Drawing.Point(91, 191);
			textBox15.Location = point;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control textBox16 = this.TextBox6;
			size = new global::System.Drawing.Size(66, 20);
			textBox16.Size = size;
			this.TextBox6.TabIndex = 7;
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label15 = this.Label6;
			point = new global::System.Drawing.Point(23, 194);
			label15.Location = point;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label16 = this.Label6;
			size = new global::System.Drawing.Size(62, 13);
			label16.Size = size;
			this.Label6.TabIndex = 8;
			this.Label6.Text = "Drivetrain";
			global::System.Windows.Forms.Control textBox17 = this.TextBox22;
			point = new global::System.Drawing.Point(91, 61);
			textBox17.Location = point;
			this.TextBox22.Name = "TextBox22";
			global::System.Windows.Forms.Control textBox18 = this.TextBox22;
			size = new global::System.Drawing.Size(66, 20);
			textBox18.Size = size;
			this.TextBox22.TabIndex = 50;
			global::System.Windows.Forms.Control button15 = this.Button7;
			point = new global::System.Drawing.Point(163, 111);
			button15.Location = point;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control button16 = this.Button7;
			size = new global::System.Drawing.Size(26, 23);
			button16.Size = size;
			this.Button7.TabIndex = 13;
			this.Button7.Text = "?";
			this.Button7.UseVisualStyleBackColor = true;
			this.Button4.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 192);
			global::System.Windows.Forms.Control button17 = this.Button4;
			point = new global::System.Drawing.Point(44, 243);
			button17.Location = point;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control button18 = this.Button4;
			size = new global::System.Drawing.Size(156, 20);
			button18.Size = size;
			this.Button4.TabIndex = 12;
			this.Button4.Text = "Force torque split editor install";
			this.Button4.UseVisualStyleBackColor = false;
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label17 = this.Label3;
			point = new global::System.Drawing.Point(39, 116);
			label17.Location = point;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label18 = this.Label3;
			size = new global::System.Drawing.Size(46, 13);
			label18.Size = size;
			this.Label3.TabIndex = 1;
			this.Label3.Text = "Engine";
			global::System.Windows.Forms.Control textBox19 = this.EngineCodeTextBox;
			point = new global::System.Drawing.Point(91, 113);
			textBox19.Location = point;
			this.EngineCodeTextBox.Name = "TextBox3";
			global::System.Windows.Forms.Control textBox20 = this.EngineCodeTextBox;
			size = new global::System.Drawing.Size(66, 20);
			textBox20.Size = size;
			this.EngineCodeTextBox.TabIndex = 2;
			global::System.Windows.Forms.Control textBox21 = this.TextBox20;
			point = new global::System.Drawing.Point(91, 9);
			textBox21.Location = point;
			this.TextBox20.Name = "TextBox20";
			global::System.Windows.Forms.Control textBox22 = this.TextBox20;
			size = new global::System.Drawing.Size(66, 20);
			textBox22.Size = size;
			this.TextBox20.TabIndex = 46;
			this.Label33.AutoSize = true;
			this.Label33.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label33.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label19 = this.Label33;
			point = new global::System.Drawing.Point(13, 38);
			label19.Location = point;
			this.Label33.Name = "Label33";
			global::System.Windows.Forms.Control label20 = this.Label33;
			size = new global::System.Drawing.Size(72, 13);
			label20.Size = size;
			this.Label33.TabIndex = 47;
			this.Label33.Text = "Suspension";
			this.Label32.AutoSize = true;
			this.Label32.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label32.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label21 = this.Label32;
			point = new global::System.Drawing.Point(28, 12);
			label21.Location = point;
			this.Label32.Name = "Label32";
			global::System.Windows.Forms.Control label22 = this.Label32;
			size = new global::System.Drawing.Size(57, 13);
			label22.Size = size;
			this.Label32.TabIndex = 45;
			this.Label32.Text = "Car body";
			global::System.Windows.Forms.Control textBox23 = this.TextBox21;
			point = new global::System.Drawing.Point(91, 35);
			textBox23.Location = point;
			this.TextBox21.Name = "TextBox21";
			global::System.Windows.Forms.Control textBox24 = this.TextBox21;
			size = new global::System.Drawing.Size(66, 20);
			textBox24.Size = size;
			this.TextBox21.TabIndex = 48;
			this.Label34.AutoSize = true;
			this.Label34.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label34.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label23 = this.Label34;
			point = new global::System.Drawing.Point(54, 64);
			label23.Location = point;
			this.Label34.Name = "Label34";
			global::System.Windows.Forms.Control label24 = this.Label34;
			size = new global::System.Drawing.Size(31, 13);
			label24.Size = size;
			this.Label34.TabIndex = 49;
			this.Label34.Text = "LSD";
			this.GroupBox8.Controls.Add(this.Label14);
			this.GroupBox8.Controls.Add(this.Button11);
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox8;
			point = new global::System.Drawing.Point(6, 153);
			groupBox9.Location = point;
			this.GroupBox8.Name = "GroupBox8";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox8;
			size = new global::System.Drawing.Size(221, 42);
			groupBox10.Size = size;
			this.GroupBox8.TabIndex = 43;
			this.GroupBox8.TabStop = false;
			this.GroupBox8.Text = "Transmission";
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label14.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label25 = this.Label14;
			point = new global::System.Drawing.Point(6, 16);
			label25.Location = point;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label26 = this.Label14;
			size = new global::System.Drawing.Size(116, 13);
			label26.Size = size;
			this.Label14.TabIndex = 26;
			this.Label14.Text = "Transmission editor";
			this.Button11.BackColor = global::System.Drawing.Color.Red;
			this.Button11.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button19 = this.Button11;
			point = new global::System.Drawing.Point(128, 11);
			button19.Location = point;
			this.Button11.Name = "Button11";
			global::System.Windows.Forms.Control button20 = this.Button11;
			size = new global::System.Drawing.Size(75, 23);
			button20.Size = size;
			this.Button11.TabIndex = 27;
			this.Button11.Text = "Open";
			this.Button11.UseVisualStyleBackColor = false;
			this.GroupBox7.Controls.Add(this.TextBox13);
			this.GroupBox7.Controls.Add(this.Label16);
			this.GroupBox7.Controls.Add(this.TextBox12);
			this.GroupBox7.Controls.Add(this.Label17);
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox7;
			point = new global::System.Drawing.Point(6, 62);
			groupBox11.Location = point;
			this.GroupBox7.Name = "GroupBox7";
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox7;
			size = new global::System.Drawing.Size(221, 39);
			groupBox12.Size = size;
			this.GroupBox7.TabIndex = 42;
			this.GroupBox7.TabStop = false;
			this.GroupBox7.Text = "Downforce";
			global::System.Windows.Forms.Control textBox25 = this.TextBox13;
			point = new global::System.Drawing.Point(45, 13);
			textBox25.Location = point;
			this.TextBox13.Name = "TextBox13";
			global::System.Windows.Forms.Control textBox26 = this.TextBox13;
			size = new global::System.Drawing.Size(38, 20);
			textBox26.Size = size;
			this.TextBox13.TabIndex = 32;
			this.Label16.AutoSize = true;
			this.Label16.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label16.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label27 = this.Label16;
			point = new global::System.Drawing.Point(6, 16);
			label27.Location = point;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control label28 = this.Label16;
			size = new global::System.Drawing.Size(33, 13);
			label28.Size = size;
			this.Label16.TabIndex = 31;
			this.Label16.Text = "Aero";
			global::System.Windows.Forms.Control textBox27 = this.TextBox12;
			point = new global::System.Drawing.Point(105, 13);
			textBox27.Location = point;
			this.TextBox12.Name = "TextBox12";
			global::System.Windows.Forms.Control textBox28 = this.TextBox12;
			size = new global::System.Drawing.Size(38, 20);
			textBox28.Size = size;
			this.TextBox12.TabIndex = 33;
			this.Label17.AutoSize = true;
			global::System.Windows.Forms.Control label29 = this.Label17;
			point = new global::System.Drawing.Point(89, 16);
			label29.Location = point;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control label30 = this.Label17;
			size = new global::System.Drawing.Size(10, 13);
			label30.Size = size;
			this.Label17.TabIndex = 34;
			this.Label17.Text = ":";
			this.GroupBox6.Controls.Add(this.Button23);
			this.GroupBox6.Controls.Add(this.CheckBox7);
			this.GroupBox6.Controls.Add(this.CheckBox6);
			this.GroupBox6.Controls.Add(this.CheckBox5);
			this.GroupBox6.Controls.Add(this.Label12);
			this.GroupBox6.Controls.Add(this.TextBox9);
			this.GroupBox6.Controls.Add(this.Button10);
			global::System.Windows.Forms.Control groupBox13 = this.GroupBox6;
			point = new global::System.Drawing.Point(6, 201);
			groupBox13.Location = point;
			this.GroupBox6.Name = "GroupBox6";
			global::System.Windows.Forms.Control groupBox14 = this.GroupBox6;
			size = new global::System.Drawing.Size(221, 103);
			groupBox14.Size = size;
			this.GroupBox6.TabIndex = 41;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Visual mods";
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label31 = this.Label12;
			point = new global::System.Drawing.Point(6, 16);
			label31.Location = point;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label32 = this.Label12;
			size = new global::System.Drawing.Size(94, 13);
			label32.Size = size;
			this.Label12.TabIndex = 21;
			this.Label12.Text = "Remove spoiler";
			global::System.Windows.Forms.Control textBox29 = this.TextBox9;
			point = new global::System.Drawing.Point(106, 13);
			textBox29.Location = point;
			this.TextBox9.Name = "TextBox9";
			global::System.Windows.Forms.Control textBox30 = this.TextBox9;
			size = new global::System.Drawing.Size(38, 20);
			textBox30.Size = size;
			this.TextBox9.TabIndex = 22;
			global::System.Windows.Forms.Control button21 = this.Button10;
			point = new global::System.Drawing.Point(150, 11);
			button21.Location = point;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control button22 = this.Button10;
			size = new global::System.Drawing.Size(26, 23);
			button22.Size = size;
			this.Button10.TabIndex = 23;
			this.Button10.Text = "?";
			this.Button10.UseVisualStyleBackColor = true;
			this.GroupBox5.Controls.Add(this.Button17);
			this.GroupBox5.Controls.Add(this.Button16);
			this.GroupBox5.Controls.Add(this.Label15);
			this.GroupBox5.Controls.Add(this.TextBox11);
			this.GroupBox5.Controls.Add(this.TextBox19);
			this.GroupBox5.Controls.Add(this.Label31);
			this.GroupBox5.Controls.Add(this.CheckBox2);
			global::System.Windows.Forms.Control groupBox15 = this.GroupBox5;
			point = new global::System.Drawing.Point(233, 282);
			groupBox15.Location = point;
			this.GroupBox5.Name = "GroupBox5";
			global::System.Windows.Forms.Control groupBox16 = this.GroupBox5;
			size = new global::System.Drawing.Size(219, 96);
			groupBox16.Size = size;
			this.GroupBox5.TabIndex = 40;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Performance multipliers";
			global::System.Windows.Forms.Control button23 = this.Button17;
			point = new global::System.Drawing.Point(181, 61);
			button23.Location = point;
			this.Button17.Name = "Button17";
			global::System.Windows.Forms.Control button24 = this.Button17;
			size = new global::System.Drawing.Size(26, 23);
			button24.Size = size;
			this.Button17.TabIndex = 53;
			this.Button17.Text = "?";
			this.Button17.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button25 = this.Button16;
			point = new global::System.Drawing.Point(165, 13);
			button25.Location = point;
			this.Button16.Name = "Button16";
			global::System.Windows.Forms.Control button26 = this.Button16;
			size = new global::System.Drawing.Size(24, 46);
			button26.Size = size;
			this.Button16.TabIndex = 37;
			this.Button16.Text = "?";
			this.Button16.UseVisualStyleBackColor = true;
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label15.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label33 = this.Label15;
			point = new global::System.Drawing.Point(22, 16);
			label33.Location = point;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label34 = this.Label15;
			size = new global::System.Drawing.Size(40, 13);
			label34.Size = size;
			this.Label15.TabIndex = 28;
			this.Label15.Text = "Turbo";
			global::System.Windows.Forms.Control textBox31 = this.TextBox11;
			point = new global::System.Drawing.Point(68, 13);
			textBox31.Location = point;
			this.TextBox11.Name = "TextBox11";
			global::System.Windows.Forms.Control textBox32 = this.TextBox11;
			size = new global::System.Drawing.Size(91, 20);
			textBox32.Size = size;
			this.TextBox11.TabIndex = 29;
			global::System.Windows.Forms.Control textBox33 = this.TextBox19;
			point = new global::System.Drawing.Point(68, 39);
			textBox33.Location = point;
			this.TextBox19.Name = "TextBox19";
			global::System.Windows.Forms.Control textBox34 = this.TextBox19;
			size = new global::System.Drawing.Size(91, 20);
			textBox34.Size = size;
			this.TextBox19.TabIndex = 36;
			this.Label31.AutoSize = true;
			this.Label31.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label31.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label35 = this.Label31;
			point = new global::System.Drawing.Point(10, 42);
			label35.Location = point;
			this.Label31.Name = "Label31";
			global::System.Windows.Forms.Control label36 = this.Label31;
			size = new global::System.Drawing.Size(52, 13);
			label36.Size = size;
			this.Label31.TabIndex = 35;
			this.Label31.Text = "Exhaust";
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox2.ForeColor = global::System.Drawing.Color.Lime;
			global::System.Windows.Forms.Control checkBox = this.CheckBox2;
			point = new global::System.Drawing.Point(13, 65);
			checkBox.Location = point;
			this.CheckBox2.Name = "CheckBox2";
			global::System.Windows.Forms.Control checkBox2 = this.CheckBox2;
			size = new global::System.Drawing.Size(162, 17);
			checkBox2.Size = size;
			this.CheckBox2.TabIndex = 30;
			this.CheckBox2.Text = "Samba-like performance";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.GroupBox4.Controls.Add(this.CheckBox3);
			this.GroupBox4.Controls.Add(this.Button14);
			this.GroupBox4.Controls.Add(this.CheckBox1);
			this.GroupBox4.Controls.Add(this.Button9);
			global::System.Windows.Forms.Control groupBox17 = this.GroupBox4;
			point = new global::System.Drawing.Point(6, 310);
			groupBox17.Location = point;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox18 = this.GroupBox4;
			size = new global::System.Drawing.Size(221, 68);
			groupBox18.Size = size;
			this.GroupBox4.TabIndex = 39;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "Reset protection";
			this.CheckBox3.AutoSize = true;
			global::System.Windows.Forms.Control checkBox3 = this.CheckBox3;
			point = new global::System.Drawing.Point(6, 19);
			checkBox3.Location = point;
			this.CheckBox3.Name = "CheckBox3";
			global::System.Windows.Forms.Control checkBox4 = this.CheckBox3;
			size = new global::System.Drawing.Size(181, 17);
			checkBox4.Size = size;
			this.CheckBox3.TabIndex = 37;
			this.CheckBox3.Text = "Add LUCA bytes before FF block";
			this.CheckBox3.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button27 = this.Button14;
			point = new global::System.Drawing.Point(186, 15);
			button27.Location = point;
			this.Button14.Name = "Button14";
			global::System.Windows.Forms.Control button28 = this.Button14;
			size = new global::System.Drawing.Size(26, 23);
			button28.Size = size;
			this.Button14.TabIndex = 38;
			this.Button14.Text = "?";
			this.Button14.UseVisualStyleBackColor = true;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Checked = true;
			this.CheckBox1.CheckState = global::System.Windows.Forms.CheckState.Checked;
			global::System.Windows.Forms.Control checkBox5 = this.CheckBox1;
			point = new global::System.Drawing.Point(6, 42);
			checkBox5.Location = point;
			this.CheckBox1.Name = "CheckBox1";
			global::System.Windows.Forms.Control checkBox6 = this.CheckBox1;
			size = new global::System.Drawing.Size(160, 17);
			checkBox6.Size = size;
			this.CheckBox1.TabIndex = 15;
			this.CheckBox1.Text = "Add 74 byte before FF block";
			this.CheckBox1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button29 = this.Button9;
			point = new global::System.Drawing.Point(172, 38);
			button29.Location = point;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control button30 = this.Button9;
			size = new global::System.Drawing.Size(26, 23);
			button30.Size = size;
			this.Button9.TabIndex = 16;
			this.Button9.Text = "?";
			this.Button9.UseVisualStyleBackColor = true;
			this.GroupBox3.Controls.Add(this.Label9);
			this.GroupBox3.Controls.Add(this.Label8);
			this.GroupBox3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox3.ForeColor = global::System.Drawing.Color.Fuchsia;
			global::System.Windows.Forms.Control groupBox19 = this.GroupBox3;
			point = new global::System.Drawing.Point(12, 7);
			groupBox19.Location = point;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox20 = this.GroupBox3;
			size = new global::System.Drawing.Size(122, 49);
			groupBox20.Size = size;
			this.GroupBox3.TabIndex = 11;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Key";
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label37 = this.Label9;
			point = new global::System.Drawing.Point(6, 33);
			label37.Location = point;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label38 = this.Label9;
			size = new global::System.Drawing.Size(79, 13);
			label38.Size = size;
			this.Label9.TabIndex = 12;
			this.Label9.Text = "Decimal only";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label39 = this.Label8;
			point = new global::System.Drawing.Point(6, 16);
			label39.Location = point;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label40 = this.Label8;
			size = new global::System.Drawing.Size(56, 13);
			label40.Size = size;
			this.Label8.TabIndex = 12;
			this.Label8.Text = "Hex only";
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Comic Sans MS", 8.25f, global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label41 = this.Label7;
			point = new global::System.Drawing.Point(3, 381);
			label41.Location = point;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label42 = this.Label7;
			size = new global::System.Drawing.Size(49, 15);
			label42.Size = size;
			this.Label7.TabIndex = 10;
			this.Label7.Text = "??Car??";
			this.TabPage3.Controls.Add(this.GroupBox14);
			this.TabPage3.Controls.Add(this.GroupBox13);
			this.TabPage3.Controls.Add(this.GroupBox12);
			this.TabPage3.Controls.Add(this.GroupBox11);
			global::System.Windows.Forms.TabPage tabPage4 = this.TabPage3;
			point = new global::System.Drawing.Point(4, 22);
			tabPage4.Location = point;
			this.TabPage3.Name = "TabPage3";
			global::System.Windows.Forms.Control tabPage5 = this.TabPage3;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage5.Padding = padding;
			global::System.Windows.Forms.Control tabPage6 = this.TabPage3;
			size = new global::System.Drawing.Size(458, 399);
			tabPage6.Size = size;
			this.TabPage3.TabIndex = 1;
			this.TabPage3.Text = "Page 2";
			this.TabPage3.UseVisualStyleBackColor = true;
			this.GroupBox14.Controls.Add(this.Button21);
			this.GroupBox14.Controls.Add(this.Button20);
			this.GroupBox14.Controls.Add(this.Label39);
			global::System.Windows.Forms.Control groupBox21 = this.GroupBox14;
			point = new global::System.Drawing.Point(245, 80);
			groupBox21.Location = point;
			this.GroupBox14.Name = "GroupBox14";
			global::System.Windows.Forms.Control groupBox22 = this.GroupBox14;
			size = new global::System.Drawing.Size(207, 100);
			groupBox22.Size = size;
			this.GroupBox14.TabIndex = 48;
			this.GroupBox14.TabStop = false;
			this.GroupBox14.Text = "Under development (EXPERIMENTAL)";
			this.Button21.BackColor = global::System.Drawing.Color.FromArgb(255, 192, 192);
			global::System.Windows.Forms.Control button31 = this.Button21;
			point = new global::System.Drawing.Point(73, 32);
			button31.Location = point;
			this.Button21.Name = "Button21";
			global::System.Windows.Forms.Control button32 = this.Button21;
			size = new global::System.Drawing.Size(55, 23);
			button32.Size = size;
			this.Button21.TabIndex = 2;
			this.Button21.Text = "Uninstall";
			this.Button21.UseVisualStyleBackColor = false;
			this.Button20.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.Button20.ForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control button33 = this.Button20;
			point = new global::System.Drawing.Point(6, 32);
			button33.Location = point;
			this.Button20.Name = "Button20";
			global::System.Windows.Forms.Control button34 = this.Button20;
			size = new global::System.Drawing.Size(61, 23);
			button34.Size = size;
			this.Button20.TabIndex = 1;
			this.Button20.Text = "Install";
			this.Button20.UseVisualStyleBackColor = false;
			this.Label39.AutoSize = true;
			global::System.Windows.Forms.Control label43 = this.Label39;
			point = new global::System.Drawing.Point(6, 16);
			label43.Location = point;
			this.Label39.Name = "Label39";
			global::System.Windows.Forms.Control label44 = this.Label39;
			size = new global::System.Drawing.Size(68, 13);
			label44.Size = size;
			this.Label39.TabIndex = 0;
			this.Label39.Text = "Transmission";
			this.GroupBox13.Controls.Add(this.CheckBox4);
			this.GroupBox13.Controls.Add(this.TextBox24);
			this.GroupBox13.Controls.Add(this.Label38);
			global::System.Windows.Forms.Control groupBox23 = this.GroupBox13;
			point = new global::System.Drawing.Point(245, 6);
			groupBox23.Location = point;
			this.GroupBox13.Name = "GroupBox13";
			global::System.Windows.Forms.Control groupBox24 = this.GroupBox13;
			size = new global::System.Drawing.Size(210, 68);
			groupBox24.Size = size;
			this.GroupBox13.TabIndex = 47;
			this.GroupBox13.TabStop = false;
			this.GroupBox13.Text = "Weight hack";
			this.CheckBox4.AutoSize = true;
			global::System.Windows.Forms.Control checkBox7 = this.CheckBox4;
			point = new global::System.Drawing.Point(9, 38);
			checkBox7.Location = point;
			this.CheckBox4.Name = "CheckBox4";
			global::System.Windows.Forms.Control checkBox8 = this.CheckBox4;
			size = new global::System.Drawing.Size(172, 17);
			checkBox8.Size = size;
			this.CheckBox4.TabIndex = 46;
			this.CheckBox4.Text = "Install stage 3 weight reduction";
			this.CheckBox4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control textBox35 = this.TextBox24;
			point = new global::System.Drawing.Point(113, 13);
			textBox35.Location = point;
			this.TextBox24.Name = "TextBox24";
			global::System.Windows.Forms.Control textBox36 = this.TextBox24;
			size = new global::System.Drawing.Size(91, 20);
			textBox36.Size = size;
			this.TextBox24.TabIndex = 41;
			this.Label38.AutoSize = true;
			this.Label38.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label38.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label45 = this.Label38;
			point = new global::System.Drawing.Point(6, 16);
			label45.Location = point;
			this.Label38.Name = "Label38";
			global::System.Windows.Forms.Control label46 = this.Label38;
			size = new global::System.Drawing.Size(101, 13);
			label46.Size = size;
			this.Label38.TabIndex = 45;
			this.Label38.Text = "Weight multiplier";
			this.GroupBox12.Controls.Add(this.Label13);
			this.GroupBox12.Controls.Add(this.TextBox10);
			this.GroupBox12.Controls.Add(this.TextBox16);
			this.GroupBox12.Controls.Add(this.Label20);
			global::System.Windows.Forms.Control groupBox25 = this.GroupBox12;
			point = new global::System.Drawing.Point(6, 102);
			groupBox25.Location = point;
			this.GroupBox12.Name = "GroupBox12";
			global::System.Windows.Forms.Control groupBox26 = this.GroupBox12;
			size = new global::System.Drawing.Size(233, 72);
			groupBox26.Size = size;
			this.GroupBox12.TabIndex = 46;
			this.GroupBox12.TabStop = false;
			this.GroupBox12.Text = "Other";
			this.Label13.AutoSize = true;
			this.Label13.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label13.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label47 = this.Label13;
			point = new global::System.Drawing.Point(6, 16);
			label47.Location = point;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control label48 = this.Label13;
			size = new global::System.Drawing.Size(36, 13);
			label48.Size = size;
			this.Label13.TabIndex = 24;
			this.Label13.Text = "Paint";
			global::System.Windows.Forms.Control textBox37 = this.TextBox10;
			point = new global::System.Drawing.Point(48, 13);
			textBox37.Location = point;
			this.TextBox10.Name = "TextBox10";
			global::System.Windows.Forms.Control textBox38 = this.TextBox10;
			size = new global::System.Drawing.Size(91, 20);
			textBox38.Size = size;
			this.TextBox10.TabIndex = 25;
			global::System.Windows.Forms.Control textBox39 = this.TextBox16;
			point = new global::System.Drawing.Point(48, 39);
			textBox39.Location = point;
			this.TextBox16.Name = "TextBox16";
			global::System.Windows.Forms.Control textBox40 = this.TextBox16;
			size = new global::System.Drawing.Size(42, 20);
			textBox40.Size = size;
			this.TextBox16.TabIndex = 40;
			this.Label20.AutoSize = true;
			this.Label20.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label20.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label49 = this.Label20;
			point = new global::System.Drawing.Point(12, 42);
			label49.Location = point;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control label50 = this.Label20;
			size = new global::System.Drawing.Size(30, 13);
			label50.Size = size;
			this.Label20.TabIndex = 39;
			this.Label20.Text = "Grip";
			this.GroupBox11.Controls.Add(this.Button19);
			this.GroupBox11.Controls.Add(this.Label18);
			this.GroupBox11.Controls.Add(this.TextBox14);
			this.GroupBox11.Controls.Add(this.Label22);
			this.GroupBox11.Controls.Add(this.TextBox15);
			this.GroupBox11.Controls.Add(this.TextBox17);
			this.GroupBox11.Controls.Add(this.Label19);
			this.GroupBox11.Controls.Add(this.TextBox18);
			this.GroupBox11.Controls.Add(this.Label21);
			global::System.Windows.Forms.Control groupBox27 = this.GroupBox11;
			point = new global::System.Drawing.Point(6, 6);
			groupBox27.Location = point;
			this.GroupBox11.Name = "GroupBox11";
			global::System.Windows.Forms.Control groupBox28 = this.GroupBox11;
			size = new global::System.Drawing.Size(233, 90);
			groupBox28.Size = size;
			this.GroupBox11.TabIndex = 45;
			this.GroupBox11.TabStop = false;
			this.GroupBox11.Text = "Suspension";
			this.Button19.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 255);
			this.Button19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button19.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			global::System.Windows.Forms.Control button35 = this.Button19;
			point = new global::System.Drawing.Point(123, 61);
			button35.Location = point;
			this.Button19.Name = "Button19";
			global::System.Windows.Forms.Control button36 = this.Button19;
			size = new global::System.Drawing.Size(75, 23);
			button36.Size = size;
			this.Button19.TabIndex = 42;
			this.Button19.Text = "Slam car";
			this.Button19.UseVisualStyleBackColor = false;
			this.Label18.AutoSize = true;
			this.Label18.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label18.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label51 = this.Label18;
			point = new global::System.Drawing.Point(6, 16);
			label51.Location = point;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control label52 = this.Label18;
			size = new global::System.Drawing.Size(111, 13);
			label52.Size = size;
			this.Label18.TabIndex = 35;
			this.Label18.Text = "Suspension height";
			global::System.Windows.Forms.Control textBox41 = this.TextBox14;
			point = new global::System.Drawing.Point(123, 13);
			textBox41.Location = point;
			this.TextBox14.Name = "TextBox14";
			global::System.Windows.Forms.Control textBox42 = this.TextBox14;
			size = new global::System.Drawing.Size(42, 20);
			textBox42.Size = size;
			this.TextBox14.TabIndex = 36;
			this.Label22.AutoSize = true;
			global::System.Windows.Forms.Control label53 = this.Label22;
			point = new global::System.Drawing.Point(171, 42);
			label53.Location = point;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control label54 = this.Label22;
			size = new global::System.Drawing.Size(10, 13);
			label54.Size = size;
			this.Label22.TabIndex = 44;
			this.Label22.Text = ":";
			global::System.Windows.Forms.Control textBox43 = this.TextBox15;
			point = new global::System.Drawing.Point(187, 13);
			textBox43.Location = point;
			this.TextBox15.Name = "TextBox15";
			global::System.Windows.Forms.Control textBox44 = this.TextBox15;
			size = new global::System.Drawing.Size(42, 20);
			textBox44.Size = size;
			this.TextBox15.TabIndex = 37;
			global::System.Windows.Forms.Control textBox45 = this.TextBox17;
			point = new global::System.Drawing.Point(187, 39);
			textBox45.Location = point;
			this.TextBox17.Name = "TextBox17";
			global::System.Windows.Forms.Control textBox46 = this.TextBox17;
			size = new global::System.Drawing.Size(42, 20);
			textBox46.Size = size;
			this.TextBox17.TabIndex = 43;
			this.Label19.AutoSize = true;
			global::System.Windows.Forms.Control label55 = this.Label19;
			point = new global::System.Drawing.Point(171, 16);
			label55.Location = point;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control label56 = this.Label19;
			size = new global::System.Drawing.Size(10, 13);
			label56.Size = size;
			this.Label19.TabIndex = 38;
			this.Label19.Text = ":";
			global::System.Windows.Forms.Control textBox47 = this.TextBox18;
			point = new global::System.Drawing.Point(123, 39);
			textBox47.Location = point;
			this.TextBox18.Name = "TextBox18";
			global::System.Windows.Forms.Control textBox48 = this.TextBox18;
			size = new global::System.Drawing.Size(42, 20);
			textBox48.Size = size;
			this.TextBox18.TabIndex = 42;
			this.Label21.AutoSize = true;
			this.Label21.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label21.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label57 = this.Label21;
			point = new global::System.Drawing.Point(48, 42);
			label57.Location = point;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control label58 = this.Label21;
			size = new global::System.Drawing.Size(69, 13);
			label58.Size = size;
			this.Label21.TabIndex = 41;
			this.Label21.Text = "Spring rate";
			this.TabControl1.Controls.Add(this.TabPage1);
			this.TabControl1.Controls.Add(this.TabPage4);
			global::System.Windows.Forms.Control tabControl3 = this.TabControl1;
			point = new global::System.Drawing.Point(13, 121);
			tabControl3.Location = point;
			this.TabControl1.Name = "TabControl1";
			this.TabControl1.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabControl4 = this.TabControl1;
			size = new global::System.Drawing.Size(368, 338);
			tabControl4.Size = size;
			this.TabControl1.TabIndex = 2;
			this.TabPage1.Controls.Add(this.Label37);
			this.TabPage1.Controls.Add(this.Button12);
			this.TabPage1.Controls.Add(this.Label30);
			this.TabPage1.Controls.Add(this.ComboBox8);
			this.TabPage1.Controls.Add(this.Label29);
			this.TabPage1.Controls.Add(this.ComboBox7);
			this.TabPage1.Controls.Add(this.Label28);
			this.TabPage1.Controls.Add(this.ComboBox6);
			this.TabPage1.Controls.Add(this.Label27);
			this.TabPage1.Controls.Add(this.ComboBox5);
			this.TabPage1.Controls.Add(this.Label26);
			this.TabPage1.Controls.Add(this.ComboBox4);
			this.TabPage1.Controls.Add(this.Label25);
			this.TabPage1.Controls.Add(this.ComboBox3);
			this.TabPage1.Controls.Add(this.Label24);
			this.TabPage1.Controls.Add(this.ComboBox2);
			this.TabPage1.Controls.Add(this.Label23);
			this.TabPage1.Controls.Add(this.ComboBox1);
			global::System.Windows.Forms.TabPage tabPage7 = this.TabPage1;
			point = new global::System.Drawing.Point(4, 22);
			tabPage7.Location = point;
			this.TabPage1.Name = "TabPage1";
			global::System.Windows.Forms.Control tabPage8 = this.TabPage1;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage8.Padding = padding;
			global::System.Windows.Forms.Control tabPage9 = this.TabPage1;
			size = new global::System.Drawing.Size(360, 312);
			tabPage9.Size = size;
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "Parts Database";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.Label37.AutoSize = true;
			global::System.Windows.Forms.Control label59 = this.Label37;
			point = new global::System.Drawing.Point(111, 272);
			label59.Location = point;
			this.Label37.Name = "Label37";
			global::System.Windows.Forms.Control label60 = this.Label37;
			size = new global::System.Drawing.Size(128, 13);
			label60.Size = size;
			this.Label37.TabIndex = 17;
			this.Label37.Text = "Look at all this free space";
			this.Button12.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 255);
			this.Button12.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button37 = this.Button12;
			point = new global::System.Drawing.Point(72, 220);
			button37.Location = point;
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control button38 = this.Button12;
			size = new global::System.Drawing.Size(282, 20);
			button38.Size = size;
			this.Button12.TabIndex = 16;
			this.Button12.Text = "Add current car to parts database";
			this.Button12.UseVisualStyleBackColor = false;
			this.Label30.AutoSize = true;
			global::System.Windows.Forms.Control label61 = this.Label30;
			point = new global::System.Drawing.Point(41, 199);
			label61.Location = point;
			this.Label30.Name = "Label30";
			global::System.Windows.Forms.Control label62 = this.Label30;
			size = new global::System.Drawing.Size(30, 13);
			label62.Size = size;
			this.Label30.TabIndex = 15;
			this.Label30.Text = "Horn";
			this.ComboBox8.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox8.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox = this.ComboBox8;
			point = new global::System.Drawing.Point(72, 195);
			comboBox.Location = point;
			this.ComboBox8.Name = "ComboBox8";
			global::System.Windows.Forms.Control comboBox2 = this.ComboBox8;
			size = new global::System.Drawing.Size(282, 21);
			comboBox2.Size = size;
			this.ComboBox8.Sorted = true;
			this.ComboBox8.TabIndex = 14;
			this.Label29.AutoSize = true;
			global::System.Windows.Forms.Control label63 = this.Label29;
			point = new global::System.Drawing.Point(43, 171);
			label63.Location = point;
			this.Label29.Name = "Label29";
			global::System.Windows.Forms.Control label64 = this.Label29;
			size = new global::System.Drawing.Size(28, 13);
			label64.Size = size;
			this.Label29.TabIndex = 13;
			this.Label29.Text = "LSD";
			this.ComboBox7.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox7.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox3 = this.ComboBox7;
			point = new global::System.Drawing.Point(72, 168);
			comboBox3.Location = point;
			this.ComboBox7.Name = "ComboBox7";
			global::System.Windows.Forms.Control comboBox4 = this.ComboBox7;
			size = new global::System.Drawing.Size(282, 21);
			comboBox4.Size = size;
			this.ComboBox7.Sorted = true;
			this.ComboBox7.TabIndex = 12;
			this.Label28.AutoSize = true;
			global::System.Windows.Forms.Control label65 = this.Label28;
			point = new global::System.Drawing.Point(40, 144);
			label65.Location = point;
			this.Label28.Name = "Label28";
			global::System.Windows.Forms.Control label66 = this.Label28;
			size = new global::System.Drawing.Size(31, 13);
			label66.Size = size;
			this.Label28.TabIndex = 11;
			this.Label28.Text = "Body";
			this.ComboBox6.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox6.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox5 = this.ComboBox6;
			point = new global::System.Drawing.Point(72, 141);
			comboBox5.Location = point;
			this.ComboBox6.Name = "ComboBox6";
			global::System.Windows.Forms.Control comboBox6 = this.ComboBox6;
			size = new global::System.Drawing.Size(282, 21);
			comboBox6.Size = size;
			this.ComboBox6.Sorted = true;
			this.ComboBox6.TabIndex = 10;
			this.Label27.AutoSize = true;
			global::System.Windows.Forms.Control label67 = this.Label27;
			point = new global::System.Drawing.Point(9, 117);
			label67.Location = point;
			this.Label27.Name = "Label27";
			global::System.Windows.Forms.Control label68 = this.Label27;
			size = new global::System.Drawing.Size(62, 13);
			label68.Size = size;
			this.Label27.TabIndex = 9;
			this.Label27.Text = "Suspension";
			this.ComboBox5.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox5.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox7 = this.ComboBox5;
			point = new global::System.Drawing.Point(72, 114);
			comboBox7.Location = point;
			this.ComboBox5.Name = "ComboBox5";
			global::System.Windows.Forms.Control comboBox8 = this.ComboBox5;
			size = new global::System.Drawing.Size(282, 21);
			comboBox8.Size = size;
			this.ComboBox5.Sorted = true;
			this.ComboBox5.TabIndex = 8;
			this.Label26.AutoSize = true;
			global::System.Windows.Forms.Control label69 = this.Label26;
			point = new global::System.Drawing.Point(3, 90);
			label69.Location = point;
			this.Label26.Name = "Label26";
			global::System.Windows.Forms.Control label70 = this.Label26;
			size = new global::System.Drawing.Size(68, 13);
			label70.Size = size;
			this.Label26.TabIndex = 7;
			this.Label26.Text = "Transmission";
			this.ComboBox4.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox4.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox9 = this.ComboBox4;
			point = new global::System.Drawing.Point(72, 87);
			comboBox9.Location = point;
			this.ComboBox4.Name = "ComboBox4";
			global::System.Windows.Forms.Control comboBox10 = this.ComboBox4;
			size = new global::System.Drawing.Size(282, 21);
			comboBox10.Size = size;
			this.ComboBox4.Sorted = true;
			this.ComboBox4.TabIndex = 6;
			this.Label25.AutoSize = true;
			global::System.Windows.Forms.Control label71 = this.Label25;
			point = new global::System.Drawing.Point(28, 63);
			label71.Location = point;
			this.Label25.Name = "Label25";
			global::System.Windows.Forms.Control label72 = this.Label25;
			size = new global::System.Drawing.Size(43, 13);
			label72.Size = size;
			this.Label25.TabIndex = 5;
			this.Label25.Text = "Chassis";
			this.ComboBox3.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox3.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox11 = this.ComboBox3;
			point = new global::System.Drawing.Point(72, 60);
			comboBox11.Location = point;
			this.ComboBox3.Name = "ComboBox3";
			global::System.Windows.Forms.Control comboBox12 = this.ComboBox3;
			size = new global::System.Drawing.Size(282, 21);
			comboBox12.Size = size;
			this.ComboBox3.Sorted = true;
			this.ComboBox3.TabIndex = 4;
			this.Label24.AutoSize = true;
			global::System.Windows.Forms.Control label73 = this.Label24;
			point = new global::System.Drawing.Point(19, 36);
			label73.Location = point;
			this.Label24.Name = "Label24";
			global::System.Windows.Forms.Control label74 = this.Label24;
			size = new global::System.Drawing.Size(52, 13);
			label74.Size = size;
			this.Label24.TabIndex = 3;
			this.Label24.Text = "Drivetrain";
			this.ComboBox2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox2.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox13 = this.ComboBox2;
			point = new global::System.Drawing.Point(72, 33);
			comboBox13.Location = point;
			this.ComboBox2.Name = "ComboBox2";
			global::System.Windows.Forms.Control comboBox14 = this.ComboBox2;
			size = new global::System.Drawing.Size(282, 21);
			comboBox14.Size = size;
			this.ComboBox2.Sorted = true;
			this.ComboBox2.TabIndex = 2;
			this.Label23.AutoSize = true;
			global::System.Windows.Forms.Control label75 = this.Label23;
			point = new global::System.Drawing.Point(31, 9);
			label75.Location = point;
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control label76 = this.Label23;
			size = new global::System.Drawing.Size(40, 13);
			label76.Size = size;
			this.Label23.TabIndex = 1;
			this.Label23.Text = "Engine";
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox15 = this.ComboBox1;
			point = new global::System.Drawing.Point(72, 6);
			comboBox15.Location = point;
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control comboBox16 = this.ComboBox1;
			size = new global::System.Drawing.Size(282, 21);
			comboBox16.Size = size;
			this.ComboBox1.Sorted = true;
			this.ComboBox1.TabIndex = 0;
			this.TabPage4.Controls.Add(this.Button18);
			this.TabPage4.Controls.Add(this.Button15);
			this.TabPage4.Controls.Add(this.Button13);
			this.TabPage4.Controls.Add(this.Label36);
			global::System.Windows.Forms.TabPage tabPage10 = this.TabPage4;
			point = new global::System.Drawing.Point(4, 22);
			tabPage10.Location = point;
			this.TabPage4.Name = "TabPage4";
			global::System.Windows.Forms.Control tabPage11 = this.TabPage4;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage11.Padding = padding;
			global::System.Windows.Forms.Control tabPage12 = this.TabPage4;
			size = new global::System.Drawing.Size(360, 312);
			tabPage12.Size = size;
			this.TabPage4.TabIndex = 1;
			this.TabPage4.Text = "Misc.";
			this.TabPage4.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button39 = this.Button18;
			point = new global::System.Drawing.Point(3, 65);
			button39.Location = point;
			this.Button18.Name = "Button18";
			global::System.Windows.Forms.Control button40 = this.Button18;
			size = new global::System.Drawing.Size(354, 23);
			button40.Size = size;
			this.Button18.TabIndex = 3;
			this.Button18.Text = "Get 4.2 billion credits ($$$)";
			this.Button18.UseVisualStyleBackColor = true;
			this.Button15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control button41 = this.Button15;
			point = new global::System.Drawing.Point(3, 31);
			button41.Location = point;
			this.Button15.Name = "Button15";
			global::System.Windows.Forms.Control button42 = this.Button15;
			size = new global::System.Drawing.Size(354, 28);
			button42.Size = size;
			this.Button15.TabIndex = 2;
			this.Button15.Text = "Borrow glitch (Steal car)";
			this.Button15.UseVisualStyleBackColor = true;
			this.Button13.BackColor = global::System.Drawing.Color.Red;
			this.Button13.ForeColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control button43 = this.Button13;
			point = new global::System.Drawing.Point(174, 2);
			button43.Location = point;
			this.Button13.Name = "Button13";
			global::System.Windows.Forms.Control button44 = this.Button13;
			size = new global::System.Drawing.Size(75, 23);
			button44.Size = size;
			this.Button13.TabIndex = 1;
			this.Button13.Text = "Open";
			this.Button13.UseVisualStyleBackColor = false;
			this.Label36.AutoSize = true;
			global::System.Windows.Forms.Control label77 = this.Label36;
			point = new global::System.Drawing.Point(6, 7);
			label77.Location = point;
			this.Label36.Name = "Label36";
			global::System.Windows.Forms.Control label78 = this.Label36;
			size = new global::System.Drawing.Size(162, 13);
			label78.Size = size;
			this.Label36.TabIndex = 0;
			this.Label36.Text = "Custom Samba like performance:";
			this.CheckBox5.AutoSize = true;
			this.CheckBox5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox5.ForeColor = global::System.Drawing.Color.DarkViolet;
			global::System.Windows.Forms.Control checkBox9 = this.CheckBox5;
			point = new global::System.Drawing.Point(6, 37);
			checkBox9.Location = point;
			this.CheckBox5.Name = "CheckBox5";
			global::System.Windows.Forms.Control checkBox10 = this.CheckBox5;
			size = new global::System.Drawing.Size(104, 17);
			checkBox10.Size = size;
			this.CheckBox5.TabIndex = 24;
			this.CheckBox5.Text = "Remove hood";
			this.CheckBox5.UseVisualStyleBackColor = true;
			this.CheckBox6.AutoSize = true;
			this.CheckBox6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox6.ForeColor = global::System.Drawing.Color.DarkViolet;
			global::System.Windows.Forms.Control checkBox11 = this.CheckBox6;
			point = new global::System.Drawing.Point(6, 80);
			checkBox11.Location = point;
			this.CheckBox6.Name = "CheckBox6";
			global::System.Windows.Forms.Control checkBox12 = this.CheckBox6;
			size = new global::System.Drawing.Size(143, 17);
			checkBox12.Size = size;
			this.CheckBox6.TabIndex = 25;
			this.CheckBox6.Text = "Remove rear bumper";
			this.CheckBox6.UseVisualStyleBackColor = true;
			this.CheckBox7.AutoSize = true;
			this.CheckBox7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox7.ForeColor = global::System.Drawing.Color.DarkViolet;
			global::System.Windows.Forms.Control checkBox13 = this.CheckBox7;
			point = new global::System.Drawing.Point(6, 58);
			checkBox13.Location = point;
			this.CheckBox7.Name = "CheckBox7";
			global::System.Windows.Forms.Control checkBox14 = this.CheckBox7;
			size = new global::System.Drawing.Size(147, 17);
			checkBox14.Size = size;
			this.CheckBox7.TabIndex = 26;
			this.CheckBox7.Text = "Remove front bumper";
			this.CheckBox7.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button45 = this.Button23;
			point = new global::System.Drawing.Point(150, 36);
			button45.Location = point;
			this.Button23.Name = "Button23";
			global::System.Windows.Forms.Control button46 = this.Button23;
			size = new global::System.Drawing.Size(26, 61);
			button46.Size = size;
			this.Button23.TabIndex = 27;
			this.Button23.Text = "?";
			this.Button23.UseVisualStyleBackColor = true;
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(877, 471);
			this.ClientSize = size;
			this.Controls.Add(this.TabControl1);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.MaximizeBox = false;
			this.Name = "Form1";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "GT5 Car hack workshop 2.5 (For GT5 2.14). Created by HeylonNHP";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.TabControl2.ResumeLayout(false);
			this.TabPage2.ResumeLayout(false);
			this.TabPage2.PerformLayout();
			this.GroupBox10.ResumeLayout(false);
			this.GroupBox10.PerformLayout();
			this.GroupBox9.ResumeLayout(false);
			this.GroupBox9.PerformLayout();
			this.GroupBox8.ResumeLayout(false);
			this.GroupBox8.PerformLayout();
			this.GroupBox7.ResumeLayout(false);
			this.GroupBox7.PerformLayout();
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox6.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.TabPage3.ResumeLayout(false);
			this.GroupBox14.ResumeLayout(false);
			this.GroupBox14.PerformLayout();
			this.GroupBox13.ResumeLayout(false);
			this.GroupBox13.PerformLayout();
			this.GroupBox12.ResumeLayout(false);
			this.GroupBox12.PerformLayout();
			this.GroupBox11.ResumeLayout(false);
			this.GroupBox11.PerformLayout();
			this.TabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.TabPage1.PerformLayout();
			this.TabPage4.ResumeLayout(false);
			this.TabPage4.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x0400001E RID: 30
		private global::System.ComponentModel.IContainer components;
	}
}
