namespace GT5_Car_hack_workshop_2
{
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}

			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.Button22 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.TabControl2 = new global::System.Windows.Forms.TabControl();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.GroupBox10 = new global::System.Windows.Forms.GroupBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.TorqueSplitTextBox = new global::System.Windows.Forms.TextBox();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.GroupBox9 = new global::System.Windows.Forms.GroupBox();
			this.HornCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.TransmissionCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label35 = new global::System.Windows.Forms.Label();
			this.ChassisCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.DrivetrainCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.LsdCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.EngineCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.CarBodyCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.SuspensionCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
			this.AeroFrontTextBox = new global::System.Windows.Forms.TextBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.AeroRearTextBox = new global::System.Windows.Forms.TextBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.RemoveSpoilerCodeTextBox = new global::System.Windows.Forms.TextBox();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.Button17 = new global::System.Windows.Forms.Button();
			this.Button16 = new global::System.Windows.Forms.Button();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.TurboModifierTextBox = new global::System.Windows.Forms.TextBox();
			this.ExhauseMultiplierTextBox = new global::System.Windows.Forms.TextBox();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.SambaLikePerformanceCheckbox = new global::System.Windows.Forms.CheckBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.AddLucaBytesCheckBox = new global::System.Windows.Forms.CheckBox();
			this.Button14 = new global::System.Windows.Forms.Button();
			this.Add74ByteCheckBox = new global::System.Windows.Forms.CheckBox();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.GroupBox14 = new global::System.Windows.Forms.GroupBox();
			this.Button21 = new global::System.Windows.Forms.Button();
			this.Button20 = new global::System.Windows.Forms.Button();
			this.Label39 = new global::System.Windows.Forms.Label();
			this.GroupBox13 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox4 = new global::System.Windows.Forms.CheckBox();
			this.WeightMultiplierTextBox = new global::System.Windows.Forms.TextBox();
			this.Label38 = new global::System.Windows.Forms.Label();
			this.GroupBox12 = new global::System.Windows.Forms.GroupBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.PaintCodesTextBox = new global::System.Windows.Forms.TextBox();
			this.GripTextBox = new global::System.Windows.Forms.TextBox();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.GroupBox11 = new global::System.Windows.Forms.GroupBox();
			this.Button19 = new global::System.Windows.Forms.Button();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.SuspensionHeightFrontTextBox = new global::System.Windows.Forms.TextBox();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.SuspensionHeightRearTextBox = new global::System.Windows.Forms.TextBox();
			this.SpringRateRearTextBox = new global::System.Windows.Forms.TextBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.SpringRateFrontTextBox = new global::System.Windows.Forms.TextBox();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.TabControl1 = new global::System.Windows.Forms.TabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.ComboBox8 = new global::System.Windows.Forms.ComboBox();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.ComboBox7 = new global::System.Windows.Forms.ComboBox();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.ComboBox6 = new global::System.Windows.Forms.ComboBox();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.ComboBox5 = new global::System.Windows.Forms.ComboBox();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.ComboBox4 = new global::System.Windows.Forms.ComboBox();
			this.Label25 = new global::System.Windows.Forms.Label();
			this.ComboBox3 = new global::System.Windows.Forms.ComboBox();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.Button18 = new global::System.Windows.Forms.Button();
			this.Button15 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.RemoveHoodCheckBox = new global::System.Windows.Forms.CheckBox();
			this.RemoveRearBumperCheckBox = new global::System.Windows.Forms.CheckBox();
			this.RemoveFrontBumperCheckBox = new global::System.Windows.Forms.CheckBox();
			this.Button23 = new global::System.Windows.Forms.Button();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.TabControl2.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.GroupBox10.SuspendLayout();
			this.GroupBox9.SuspendLayout();
			this.GroupBox8.SuspendLayout();
			this.GroupBox7.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.GroupBox14.SuspendLayout();
			this.GroupBox13.SuspendLayout();
			this.GroupBox12.SuspendLayout();
			this.GroupBox11.SuspendLayout();
			this.TabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.SuspendLayout();
			this.GroupBox1.Controls.Add(this.Button22);
			this.GroupBox1.Controls.Add(this.Button5);
			this.GroupBox1.Controls.Add(this.Label2);
			this.GroupBox1.Controls.Add(this.TextBox2);
			this.GroupBox1.Controls.Add(this.Button3);
			this.GroupBox1.Controls.Add(this.Button2);
			this.GroupBox1.Controls.Add(this.Button1);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.TextBox1);
			this.GroupBox1.Location = new global::System.Drawing.Point(13, 13);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(368, 101);
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Before and after you start hacking";
			this.Button22.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 192);
			this.Button22.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Button22.Location = new global::System.Drawing.Point(300, 70);
			this.Button22.Name = "Button22";
			this.Button22.Size = new global::System.Drawing.Size(62, 23);
			this.Button22.TabIndex = 8;
			this.Button22.Text = "About";
			this.Button22.UseVisualStyleBackColor = false;
			this.Button22.Click += new System.EventHandler(this.Button22_Click);
			this.Button5.BackColor = global::System.Drawing.Color.FromArgb(192, 192, 255);
			this.Button5.Location = new global::System.Drawing.Point(183, 70);
			this.Button5.Name = "Button5";
			this.Button5.Size = new global::System.Drawing.Size(75, 23);
			this.Button5.TabIndex = 7;
			this.Button5.Text = "Save only";
			this.Button5.UseVisualStyleBackColor = false;
			this.Button5.Click += new System.EventHandler(this.Button5_Click);
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(185, 20);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(58, 13);
			this.Label2.TabIndex = 6;
			this.Label2.Text = "PSN name";
			this.TextBox2.Location = new global::System.Drawing.Point(248, 17);
			this.TextBox2.Name = "TextBox2";
			this.TextBox2.Size = new global::System.Drawing.Size(113, 20);
			this.TextBox2.TabIndex = 5;
			this.Button3.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.Button3.Location = new global::System.Drawing.Point(82, 70);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(100, 23);
			this.Button3.TabIndex = 4;
			this.Button3.Text = "Save and encrypt";
			this.Button3.UseVisualStyleBackColor = false;
			this.Button3.Click += new System.EventHandler(this.Button3_Click);
			this.Button2.BackColor = global::System.Drawing.Color.FromArgb(255, 192, 192);
			this.Button2.Location = new global::System.Drawing.Point(6, 70);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(75, 23);
			this.Button2.TabIndex = 3;
			this.Button2.Text = "Load data";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button2.Click += new System.EventHandler(this.Button2_Click);
			this.Button1.BackColor = global::System.Drawing.Color.FromArgb(255, 224, 192);
			this.Button1.Location = new global::System.Drawing.Point(104, 15);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(75, 23);
			this.Button1.TabIndex = 2;
			this.Button1.Text = "Browse";
			this.Button1.UseVisualStyleBackColor = false;
			this.Button1.Click += new System.EventHandler(this.Button1_Click);
			this.Label1.AutoSize = true;
			this.Label1.Location = new global::System.Drawing.Point(6, 20);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(96, 13);
			this.Label1.TabIndex = 1;
			this.Label1.Text = "GT5.0 file location:";
			this.TextBox1.Location = new global::System.Drawing.Point(6, 44);
			this.TextBox1.Name = "TextBox1";
			this.TextBox1.Size = new global::System.Drawing.Size(355, 20);
			this.TextBox1.TabIndex = 0;
			this.GroupBox2.Controls.Add(this.TabControl2);
			this.GroupBox2.Location = new global::System.Drawing.Point(387, 13);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Size = new global::System.Drawing.Size(478, 446);
			this.GroupBox2.TabIndex = 1;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Basic hacks";
			this.TabControl2.Controls.Add(this.TabPage2);
			this.TabControl2.Controls.Add(this.TabPage3);
			this.TabControl2.Location = new global::System.Drawing.Point(6, 15);
			this.TabControl2.Name = "TabControl2";
			this.TabControl2.SelectedIndex = 0;
			this.TabControl2.Size = new global::System.Drawing.Size(466, 425);
			this.TabControl2.TabIndex = 1;
			this.TabPage2.Controls.Add(this.GroupBox10);
			this.TabPage2.Controls.Add(this.GroupBox9);
			this.TabPage2.Controls.Add(this.GroupBox8);
			this.TabPage2.Controls.Add(this.GroupBox7);
			this.TabPage2.Controls.Add(this.GroupBox6);
			this.TabPage2.Controls.Add(this.GroupBox5);
			this.TabPage2.Controls.Add(this.GroupBox4);
			this.TabPage2.Controls.Add(this.GroupBox3);
			this.TabPage2.Controls.Add(this.Label7);
			this.TabPage2.Location = new global::System.Drawing.Point(4, 22);
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage2.Size = new global::System.Drawing.Size(458, 399);
			this.TabPage2.TabIndex = 0;
			this.TabPage2.Text = "Page 1";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.GroupBox10.Controls.Add(this.Label4);
			this.GroupBox10.Controls.Add(this.TorqueSplitTextBox);
			this.GroupBox10.Controls.Add(this.TextBox5);
			this.GroupBox10.Controls.Add(this.Label5);
			this.GroupBox10.Controls.Add(this.Button8);
			this.GroupBox10.Location = new global::System.Drawing.Point(6, 107);
			this.GroupBox10.Name = "GroupBox10";
			this.GroupBox10.Size = new global::System.Drawing.Size(221, 40);
			this.GroupBox10.TabIndex = 45;
			this.GroupBox10.TabStop = false;
			this.GroupBox10.Text = "Torque";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.Red;
			this.Label4.Location = new global::System.Drawing.Point(6, 16);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(55, 13);
			this.Label4.TabIndex = 3;
			this.Label4.Text = "Tq. Split";
			this.TorqueSplitTextBox.Location = new global::System.Drawing.Point(67, 13);
			this.TorqueSplitTextBox.Name = "TextBox4";
			this.TorqueSplitTextBox.Size = new global::System.Drawing.Size(38, 20);
			this.TorqueSplitTextBox.TabIndex = 4;
			this.TorqueSplitTextBox.TextChanged += new System.EventHandler(this.TextBox4_TextChanged);
			this.TextBox5.Location = new global::System.Drawing.Point(127, 13);
			this.TextBox5.Name = "TextBox5";
			this.TextBox5.ReadOnly = true;
			this.TextBox5.Size = new global::System.Drawing.Size(38, 20);
			this.TextBox5.TabIndex = 5;
			this.Label5.AutoSize = true;
			this.Label5.Location = new global::System.Drawing.Point(111, 16);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(10, 13);
			this.Label5.TabIndex = 6;
			this.Label5.Text = ":";
			this.Button8.Location = new global::System.Drawing.Point(171, 11);
			this.Button8.Name = "Button8";
			this.Button8.Size = new global::System.Drawing.Size(26, 23);
			this.Button8.TabIndex = 14;
			this.Button8.Text = "?";
			this.Button8.UseVisualStyleBackColor = true;
			this.Button8.Click += new System.EventHandler(this.Button8_Click);
			this.GroupBox9.Controls.Add(this.HornCodeTextBox);
			this.GroupBox9.Controls.Add(this.Label11);
			this.GroupBox9.Controls.Add(this.TransmissionCodeTextBox);
			this.GroupBox9.Controls.Add(this.Label10);
			this.GroupBox9.Controls.Add(this.Label35);
			this.GroupBox9.Controls.Add(this.ChassisCodeTextBox);
			this.GroupBox9.Controls.Add(this.Button6);
			this.GroupBox9.Controls.Add(this.DrivetrainCodeTextBox);
			this.GroupBox9.Controls.Add(this.Label6);
			this.GroupBox9.Controls.Add(this.LsdCodeTextBox);
			this.GroupBox9.Controls.Add(this.Button7);
			this.GroupBox9.Controls.Add(this.Button4);
			this.GroupBox9.Controls.Add(this.Label3);
			this.GroupBox9.Controls.Add(this.EngineCodeTextBox);
			this.GroupBox9.Controls.Add(this.CarBodyCodeTextBox);
			this.GroupBox9.Controls.Add(this.Label33);
			this.GroupBox9.Controls.Add(this.Label32);
			this.GroupBox9.Controls.Add(this.SuspensionCodeTextBox);
			this.GroupBox9.Controls.Add(this.Label34);
			this.GroupBox9.Location = new global::System.Drawing.Point(233, 7);
			this.GroupBox9.Name = "GroupBox9";
			this.GroupBox9.Size = new global::System.Drawing.Size(219, 269);
			this.GroupBox9.TabIndex = 44;
			this.GroupBox9.TabStop = false;
			this.GroupBox9.Text = "Car parts";
			this.HornCodeTextBox.Location = new global::System.Drawing.Point(91, 87);
			this.HornCodeTextBox.Name = "TextBox23";
			this.HornCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.HornCodeTextBox.TabIndex = 52;
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.ForeColor = global::System.Drawing.Color.Blue;
			this.Label11.Location = new global::System.Drawing.Point(5, 142);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(80, 13);
			this.Label11.TabIndex = 19;
			this.Label11.Text = "Transmission";
			this.TransmissionCodeTextBox.Location = new global::System.Drawing.Point(91, 139);
			this.TransmissionCodeTextBox.Name = "TextBox8";
			this.TransmissionCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.TransmissionCodeTextBox.TabIndex = 20;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = global::System.Drawing.Color.Blue;
			this.Label10.Location = new global::System.Drawing.Point(35, 168);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(50, 13);
			this.Label10.TabIndex = 18;
			this.Label10.Text = "Chassis";
			this.Label35.AutoSize = true;
			this.Label35.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label35.ForeColor = global::System.Drawing.Color.Blue;
			this.Label35.Location = new global::System.Drawing.Point(51, 90);
			this.Label35.Name = "Label35";
			this.Label35.Size = new global::System.Drawing.Size(34, 13);
			this.Label35.TabIndex = 51;
			this.Label35.Text = "Horn";
			this.ChassisCodeTextBox.Location = new global::System.Drawing.Point(91, 165);
			this.ChassisCodeTextBox.Name = "TextBox7";
			this.ChassisCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.ChassisCodeTextBox.TabIndex = 17;
			this.Button6.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 255);
			this.Button6.Location = new global::System.Drawing.Point(91, 217);
			this.Button6.Name = "Button6";
			this.Button6.Size = new global::System.Drawing.Size(71, 20);
			this.Button6.TabIndex = 9;
			this.Button6.Text = "Make 4WD";
			this.Button6.UseVisualStyleBackColor = false;
			this.Button6.Click += new System.EventHandler(this.Button6_Click);
			this.DrivetrainCodeTextBox.Location = new global::System.Drawing.Point(91, 191);
			this.DrivetrainCodeTextBox.Name = "TextBox6";
			this.DrivetrainCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.DrivetrainCodeTextBox.TabIndex = 7;
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = global::System.Drawing.Color.Blue;
			this.Label6.Location = new global::System.Drawing.Point(23, 194);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(62, 13);
			this.Label6.TabIndex = 8;
			this.Label6.Text = "Drivetrain";
			this.LsdCodeTextBox.Location = new global::System.Drawing.Point(91, 61);
			this.LsdCodeTextBox.Name = "TextBox22";
			this.LsdCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.LsdCodeTextBox.TabIndex = 50;
			this.Button7.Location = new global::System.Drawing.Point(163, 111);
			this.Button7.Name = "Button7";
			this.Button7.Size = new global::System.Drawing.Size(26, 23);
			this.Button7.TabIndex = 13;
			this.Button7.Text = "?";
			this.Button7.UseVisualStyleBackColor = true;
			this.Button7.Click += new System.EventHandler(this.Button7_Click);
			this.Button4.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 192);
			this.Button4.Location = new global::System.Drawing.Point(44, 243);
			this.Button4.Name = "Button4";
			this.Button4.Size = new global::System.Drawing.Size(156, 20);
			this.Button4.TabIndex = 12;
			this.Button4.Text = "Force torque split editor install";
			this.Button4.UseVisualStyleBackColor = false;
			this.Button4.Click += new System.EventHandler(this.Button4_Click);
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.Blue;
			this.Label3.Location = new global::System.Drawing.Point(39, 116);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(46, 13);
			this.Label3.TabIndex = 1;
			this.Label3.Text = "Engine";
			this.EngineCodeTextBox.Location = new global::System.Drawing.Point(91, 113);
			this.EngineCodeTextBox.Name = "TextBox3";
			this.EngineCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.EngineCodeTextBox.TabIndex = 2;
			this.CarBodyCodeTextBox.Location = new global::System.Drawing.Point(91, 9);
			this.CarBodyCodeTextBox.Name = "TextBox20";
			this.CarBodyCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.CarBodyCodeTextBox.TabIndex = 46;
			this.Label33.AutoSize = true;
			this.Label33.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label33.ForeColor = global::System.Drawing.Color.Blue;
			this.Label33.Location = new global::System.Drawing.Point(13, 38);
			this.Label33.Name = "Label33";
			this.Label33.Size = new global::System.Drawing.Size(72, 13);
			this.Label33.TabIndex = 47;
			this.Label33.Text = "Suspension";
			this.Label32.AutoSize = true;
			this.Label32.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label32.ForeColor = global::System.Drawing.Color.Blue;
			this.Label32.Location = new global::System.Drawing.Point(28, 12);
			this.Label32.Name = "Label32";
			this.Label32.Size = new global::System.Drawing.Size(57, 13);
			this.Label32.TabIndex = 45;
			this.Label32.Text = "Car body";
			this.SuspensionCodeTextBox.Location = new global::System.Drawing.Point(91, 35);
			this.SuspensionCodeTextBox.Name = "TextBox21";
			this.SuspensionCodeTextBox.Size = new global::System.Drawing.Size(66, 20);
			this.SuspensionCodeTextBox.TabIndex = 48;
			this.Label34.AutoSize = true;
			this.Label34.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label34.ForeColor = global::System.Drawing.Color.Blue;
			this.Label34.Location = new global::System.Drawing.Point(54, 64);
			this.Label34.Name = "Label34";
			this.Label34.Size = new global::System.Drawing.Size(31, 13);
			this.Label34.TabIndex = 49;
			this.Label34.Text = "LSD";
			this.GroupBox8.Controls.Add(this.Label14);
			this.GroupBox8.Controls.Add(this.Button11);
			this.GroupBox8.Location = new global::System.Drawing.Point(6, 153);
			this.GroupBox8.Name = "GroupBox8";
			this.GroupBox8.Size = new global::System.Drawing.Size(221, 42);
			this.GroupBox8.TabIndex = 43;
			this.GroupBox8.TabStop = false;
			this.GroupBox8.Text = "Transmission";
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label14.ForeColor = global::System.Drawing.Color.Red;
			this.Label14.Location = new global::System.Drawing.Point(6, 16);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(116, 13);
			this.Label14.TabIndex = 26;
			this.Label14.Text = "Transmission editor";
			this.Button11.BackColor = global::System.Drawing.Color.Red;
			this.Button11.ForeColor = global::System.Drawing.Color.White;
			this.Button11.Location = new global::System.Drawing.Point(128, 11);
			this.Button11.Name = "Button11";
			this.Button11.Size = new global::System.Drawing.Size(75, 23);
			this.Button11.TabIndex = 27;
			this.Button11.Text = "Open";
			this.Button11.UseVisualStyleBackColor = false;
			this.Button11.Click += new System.EventHandler(this.Button11_Click);
			this.GroupBox7.Controls.Add(this.AeroFrontTextBox);
			this.GroupBox7.Controls.Add(this.Label16);
			this.GroupBox7.Controls.Add(this.AeroRearTextBox);
			this.GroupBox7.Controls.Add(this.Label17);
			this.GroupBox7.Location = new global::System.Drawing.Point(6, 62);
			this.GroupBox7.Name = "GroupBox7";
			this.GroupBox7.Size = new global::System.Drawing.Size(221, 39);
			this.GroupBox7.TabIndex = 42;
			this.GroupBox7.TabStop = false;
			this.GroupBox7.Text = "Downforce";
			this.AeroFrontTextBox.Location = new global::System.Drawing.Point(45, 13);
			this.AeroFrontTextBox.Name = "TextBox13";
			this.AeroFrontTextBox.Size = new global::System.Drawing.Size(38, 20);
			this.AeroFrontTextBox.TabIndex = 32;
			this.Label16.AutoSize = true;
			this.Label16.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label16.ForeColor = global::System.Drawing.Color.Red;
			this.Label16.Location = new global::System.Drawing.Point(6, 16);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(33, 13);
			this.Label16.TabIndex = 31;
			this.Label16.Text = "Aero";
			this.AeroRearTextBox.Location = new global::System.Drawing.Point(105, 13);
			this.AeroRearTextBox.Name = "TextBox12";
			this.AeroRearTextBox.Size = new global::System.Drawing.Size(38, 20);
			this.AeroRearTextBox.TabIndex = 33;
			this.Label17.AutoSize = true;
			this.Label17.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label17.ForeColor = global::System.Drawing.Color.Blue;
			this.Label17.Location = new global::System.Drawing.Point(89, 16);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(10, 13);
			this.Label17.TabIndex = 34;
			this.Label17.Text = ":";
			this.GroupBox6.Controls.Add(this.Button23);
			this.GroupBox6.Controls.Add(this.RemoveFrontBumperCheckBox);
			this.GroupBox6.Controls.Add(this.RemoveRearBumperCheckBox);
			this.GroupBox6.Controls.Add(this.RemoveHoodCheckBox);
			this.GroupBox6.Controls.Add(this.Label12);
			this.GroupBox6.Controls.Add(this.RemoveSpoilerCodeTextBox);
			this.GroupBox6.Controls.Add(this.Button10);
			this.GroupBox6.Location = new global::System.Drawing.Point(6, 201);
			this.GroupBox6.Name = "GroupBox6";
			this.GroupBox6.Size = new global::System.Drawing.Size(221, 103);
			this.GroupBox6.TabIndex = 41;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Visual mods";
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.ForeColor = global::System.Drawing.Color.Red;
			this.Label12.Location = new global::System.Drawing.Point(6, 16);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(94, 13);
			this.Label12.TabIndex = 21;
			this.Label12.Text = "Remove spoiler";
			this.RemoveSpoilerCodeTextBox.Location = new global::System.Drawing.Point(106, 13);
			this.RemoveSpoilerCodeTextBox.Name = "TextBox9";
			this.RemoveSpoilerCodeTextBox.Size = new global::System.Drawing.Size(38, 20);
			this.RemoveSpoilerCodeTextBox.TabIndex = 22;
			this.Button10.Location = new global::System.Drawing.Point(150, 11);
			this.Button10.Name = "Button10";
			this.Button10.Size = new global::System.Drawing.Size(26, 23);
			this.Button10.TabIndex = 23;
			this.Button10.Text = "?";
			this.Button10.UseVisualStyleBackColor = true;
			this.Button10.Click += new System.EventHandler(this.Button10_Click);
			this.GroupBox5.Controls.Add(this.Button17);
			this.GroupBox5.Controls.Add(this.Button16);
			this.GroupBox5.Controls.Add(this.Label15);
			this.GroupBox5.Controls.Add(this.TurboModifierTextBox);
			this.GroupBox5.Controls.Add(this.ExhauseMultiplierTextBox);
			this.GroupBox5.Controls.Add(this.Label31);
			this.GroupBox5.Controls.Add(this.SambaLikePerformanceCheckbox);
			this.GroupBox5.Location = new global::System.Drawing.Point(233, 282);
			this.GroupBox5.Name = "GroupBox5";
			this.GroupBox5.Size = new global::System.Drawing.Size(219, 96);
			this.GroupBox5.TabIndex = 40;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Performance multipliers";
			this.Button17.Location = new global::System.Drawing.Point(181, 61);
			this.Button17.Name = "Button17";
			this.Button17.Size = new global::System.Drawing.Size(26, 23);
			this.Button17.TabIndex = 53;
			this.Button17.Text = "?";
			this.Button17.UseVisualStyleBackColor = true;
			this.Button17.Click += new System.EventHandler(this.Button17_Click);
			this.Button16.Location = new global::System.Drawing.Point(165, 13);
			this.Button16.Name = "Button16";
			this.Button16.Size = new global::System.Drawing.Size(24, 46);
			this.Button16.TabIndex = 37;
			this.Button16.Text = "?";
			this.Button16.UseVisualStyleBackColor = true;
			this.Button16.Click += new System.EventHandler(this.Button16_Click);
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label15.ForeColor = global::System.Drawing.Color.Blue;
			this.Label15.Location = new global::System.Drawing.Point(22, 16);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(40, 13);
			this.Label15.TabIndex = 28;
			this.Label15.Text = "Turbo";
			this.TurboModifierTextBox.Location = new global::System.Drawing.Point(68, 13);
			this.TurboModifierTextBox.Name = "TextBox11";
			this.TurboModifierTextBox.Size = new global::System.Drawing.Size(91, 20);
			this.TurboModifierTextBox.TabIndex = 29;
			this.ExhauseMultiplierTextBox.Location = new global::System.Drawing.Point(68, 39);
			this.ExhauseMultiplierTextBox.Name = "TextBox19";
			this.ExhauseMultiplierTextBox.Size = new global::System.Drawing.Size(91, 20);
			this.ExhauseMultiplierTextBox.TabIndex = 36;
			this.Label31.AutoSize = true;
			this.Label31.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label31.ForeColor = global::System.Drawing.Color.Blue;
			this.Label31.Location = new global::System.Drawing.Point(10, 42);
			this.Label31.Name = "Label31";
			this.Label31.Size = new global::System.Drawing.Size(52, 13);
			this.Label31.TabIndex = 35;
			this.Label31.Text = "Exhaust";
			this.SambaLikePerformanceCheckbox.AutoSize = true;
			this.SambaLikePerformanceCheckbox.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SambaLikePerformanceCheckbox.ForeColor = global::System.Drawing.Color.Lime;
			this.SambaLikePerformanceCheckbox.Location = new global::System.Drawing.Point(13, 65);
			this.SambaLikePerformanceCheckbox.Name = "CheckBox2";
			this.SambaLikePerformanceCheckbox.Size = new global::System.Drawing.Size(162, 17);
			this.SambaLikePerformanceCheckbox.TabIndex = 30;
			this.SambaLikePerformanceCheckbox.Text = "Samba-like performance";
			this.SambaLikePerformanceCheckbox.UseVisualStyleBackColor = true;
			this.GroupBox4.Controls.Add(this.AddLucaBytesCheckBox);
			this.GroupBox4.Controls.Add(this.Button14);
			this.GroupBox4.Controls.Add(this.Add74ByteCheckBox);
			this.GroupBox4.Controls.Add(this.Button9);
			this.GroupBox4.Location = new global::System.Drawing.Point(6, 310);
			this.GroupBox4.Name = "GroupBox4";
			this.GroupBox4.Size = new global::System.Drawing.Size(221, 68);
			this.GroupBox4.TabIndex = 39;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "Reset protection";
			this.AddLucaBytesCheckBox.AutoSize = true;
			this.AddLucaBytesCheckBox.Location = new global::System.Drawing.Point(6, 19);
			this.AddLucaBytesCheckBox.Name = "CheckBox3";
			this.AddLucaBytesCheckBox.Size = new global::System.Drawing.Size(181, 17);
			this.AddLucaBytesCheckBox.TabIndex = 37;
			this.AddLucaBytesCheckBox.Text = "Add LUCA bytes before FF block";
			this.AddLucaBytesCheckBox.UseVisualStyleBackColor = true;
			this.Button14.Location = new global::System.Drawing.Point(186, 15);
			this.Button14.Name = "Button14";
			this.Button14.Size = new global::System.Drawing.Size(26, 23);
			this.Button14.TabIndex = 38;
			this.Button14.Text = "?";
			this.Button14.UseVisualStyleBackColor = true;
			this.Button14.Click += new System.EventHandler(this.Button14_Click);
			this.Add74ByteCheckBox.AutoSize = true;
			this.Add74ByteCheckBox.Checked = true;
			this.Add74ByteCheckBox.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.Add74ByteCheckBox.Location = new global::System.Drawing.Point(6, 42);
			this.Add74ByteCheckBox.Name = "CheckBox1";
			this.Add74ByteCheckBox.Size = new global::System.Drawing.Size(160, 17);
			this.Add74ByteCheckBox.TabIndex = 15;
			this.Add74ByteCheckBox.Text = "Add 74 byte before FF block";
			this.Add74ByteCheckBox.UseVisualStyleBackColor = true;
			this.Button9.Location = new global::System.Drawing.Point(172, 38);
			this.Button9.Name = "Button9";
			this.Button9.Size = new global::System.Drawing.Size(26, 23);
			this.Button9.TabIndex = 16;
			this.Button9.Text = "?";
			this.Button9.UseVisualStyleBackColor = true;
			this.Button9.Click += new System.EventHandler(this.Button9_Click);
			this.GroupBox3.Controls.Add(this.Label9);
			this.GroupBox3.Controls.Add(this.Label8);
			this.GroupBox3.Controls.Add(this.Label7);
			this.GroupBox3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox3.ForeColor = global::System.Drawing.Color.Fuchsia;
			this.GroupBox3.Location = new global::System.Drawing.Point(12, 7);
			this.GroupBox3.Name = "GroupBox3";
			this.GroupBox3.Size = new global::System.Drawing.Size(122, 49);
			this.GroupBox3.TabIndex = 11;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Key";
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.ForeColor = global::System.Drawing.Color.Red;
			this.Label9.Location = new global::System.Drawing.Point(6, 33);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(79, 13);
			this.Label9.TabIndex = 12;
			this.Label9.Text = "Decimal only";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.ForeColor = global::System.Drawing.Color.Blue;
			this.Label8.Location = new global::System.Drawing.Point(6, 16);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(56, 13);
			this.Label8.TabIndex = 12;
			this.Label8.Text = "Hex only";
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Comic Sans MS", 8.25f, global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.Location = new global::System.Drawing.Point(3, 381);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(49, 15);
			this.Label7.TabIndex = 10;
			this.Label7.Text = "??Car??";
			this.TabPage3.Controls.Add(this.GroupBox14);
			this.TabPage3.Controls.Add(this.GroupBox13);
			this.TabPage3.Controls.Add(this.GroupBox12);
			this.TabPage3.Controls.Add(this.GroupBox11);
			this.TabPage3.Location = new global::System.Drawing.Point(4, 22);
			this.TabPage3.Name = "TabPage3";
			this.TabPage3.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage3.Size = new global::System.Drawing.Size(458, 399);
			this.TabPage3.TabIndex = 1;
			this.TabPage3.Text = "Page 2";
			this.TabPage3.UseVisualStyleBackColor = true;
			this.GroupBox14.Controls.Add(this.Button21);
			this.GroupBox14.Controls.Add(this.Button20);
			this.GroupBox14.Controls.Add(this.Label39);
			this.GroupBox14.Location = new global::System.Drawing.Point(245, 80);
			this.GroupBox14.Name = "GroupBox14";
			this.GroupBox14.Size = new global::System.Drawing.Size(207, 100);
			this.GroupBox14.TabIndex = 48;
			this.GroupBox14.TabStop = false;
			this.GroupBox14.Text = "Under development (EXPERIMENTAL)";
			this.Button21.BackColor = global::System.Drawing.Color.FromArgb(255, 192, 192);
			this.Button21.Location = new global::System.Drawing.Point(73, 32);
			this.Button21.Name = "Button21";
			this.Button21.Size = new global::System.Drawing.Size(55, 23);
			this.Button21.TabIndex = 2;
			this.Button21.Text = "Uninstall";
			this.Button21.UseVisualStyleBackColor = false;
			this.Button21.Click += new System.EventHandler(this.Button21_Click);
			this.Button20.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.Button20.ForeColor = global::System.Drawing.SystemColors.ControlText;
			this.Button20.Location = new global::System.Drawing.Point(6, 32);
			this.Button20.Name = "Button20";
			this.Button20.Size = new global::System.Drawing.Size(61, 23);
			this.Button20.TabIndex = 1;
			this.Button20.Text = "Install";
			this.Button20.UseVisualStyleBackColor = false;
			this.Button20.Click += new System.EventHandler(this.Button20_Click);
			this.Label39.AutoSize = true;
			this.Label39.Location = new global::System.Drawing.Point(6, 16);
			this.Label39.Name = "Label39";
			this.Label39.Size = new global::System.Drawing.Size(68, 13);
			this.Label39.TabIndex = 0;
			this.Label39.Text = "Transmission";
			this.GroupBox13.Controls.Add(this.CheckBox4);
			this.GroupBox13.Controls.Add(this.WeightMultiplierTextBox);
			this.GroupBox13.Controls.Add(this.Label38);
			this.GroupBox13.Location = new global::System.Drawing.Point(245, 6);
			this.GroupBox13.Name = "GroupBox13";
			this.GroupBox13.Size = new global::System.Drawing.Size(210, 68);
			this.GroupBox13.TabIndex = 47;
			this.GroupBox13.TabStop = false;
			this.GroupBox13.Text = "Weight hack";
			this.CheckBox4.AutoSize = true;
			this.CheckBox4.Location = new global::System.Drawing.Point(9, 38);
			this.CheckBox4.Name = "CheckBox4";
			this.CheckBox4.Size = new global::System.Drawing.Size(172, 17);
			this.CheckBox4.TabIndex = 46;
			this.CheckBox4.Text = "Install stage 3 weight reduction";
			this.CheckBox4.UseVisualStyleBackColor = true;
			this.WeightMultiplierTextBox.Location = new global::System.Drawing.Point(113, 13);
			this.WeightMultiplierTextBox.Name = "TextBox24";
			this.WeightMultiplierTextBox.Size = new global::System.Drawing.Size(91, 20);
			this.WeightMultiplierTextBox.TabIndex = 41;
			this.Label38.AutoSize = true;
			this.Label38.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label38.ForeColor = global::System.Drawing.Color.Blue;
			this.Label38.Location = new global::System.Drawing.Point(6, 16);
			this.Label38.Name = "Label38";
			this.Label38.Size = new global::System.Drawing.Size(101, 13);
			this.Label38.TabIndex = 45;
			this.Label38.Text = "Weight multiplier";
			this.GroupBox12.Controls.Add(this.Label13);
			this.GroupBox12.Controls.Add(this.PaintCodesTextBox);
			this.GroupBox12.Controls.Add(this.GripTextBox);
			this.GroupBox12.Controls.Add(this.Label20);
			this.GroupBox12.Location = new global::System.Drawing.Point(6, 102);
			this.GroupBox12.Name = "GroupBox12";
			this.GroupBox12.Size = new global::System.Drawing.Size(233, 72);
			this.GroupBox12.TabIndex = 46;
			this.GroupBox12.TabStop = false;
			this.GroupBox12.Text = "Other";
			this.Label13.AutoSize = true;
			this.Label13.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label13.ForeColor = global::System.Drawing.Color.Blue;
			this.Label13.Location = new global::System.Drawing.Point(6, 16);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(36, 13);
			this.Label13.TabIndex = 24;
			this.Label13.Text = "Paint";
			this.PaintCodesTextBox.Location = new global::System.Drawing.Point(48, 13);
			this.PaintCodesTextBox.Name = "TextBox10";
			this.PaintCodesTextBox.Size = new global::System.Drawing.Size(91, 20);
			this.PaintCodesTextBox.TabIndex = 25;
			this.GripTextBox.Location = new global::System.Drawing.Point(48, 39);
			this.GripTextBox.Name = "TextBox16";
			this.GripTextBox.Size = new global::System.Drawing.Size(42, 20);
			this.GripTextBox.TabIndex = 40;
			this.Label20.AutoSize = true;
			this.Label20.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label20.ForeColor = global::System.Drawing.Color.Red;
			this.Label20.Location = new global::System.Drawing.Point(12, 42);
			this.Label20.Name = "Label20";
			this.Label20.Size = new global::System.Drawing.Size(30, 13);
			this.Label20.TabIndex = 39;
			this.Label20.Text = "Grip";
			this.GroupBox11.Controls.Add(this.Button19);
			this.GroupBox11.Controls.Add(this.Label18);
			this.GroupBox11.Controls.Add(this.SuspensionHeightFrontTextBox);
			this.GroupBox11.Controls.Add(this.Label22);
			this.GroupBox11.Controls.Add(this.SuspensionHeightRearTextBox);
			this.GroupBox11.Controls.Add(this.SpringRateRearTextBox);
			this.GroupBox11.Controls.Add(this.Label19);
			this.GroupBox11.Controls.Add(this.SpringRateFrontTextBox);
			this.GroupBox11.Controls.Add(this.Label21);
			this.GroupBox11.Location = new global::System.Drawing.Point(6, 6);
			this.GroupBox11.Name = "GroupBox11";
			this.GroupBox11.Size = new global::System.Drawing.Size(233, 90);
			this.GroupBox11.TabIndex = 45;
			this.GroupBox11.TabStop = false;
			this.GroupBox11.Text = "Suspension";
			this.Button19.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 255);
			this.Button19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button19.ForeColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			this.Button19.Location = new global::System.Drawing.Point(123, 61);
			this.Button19.Name = "Button19";
			this.Button19.Size = new global::System.Drawing.Size(75, 23);
			this.Button19.TabIndex = 42;
			this.Button19.Text = "Slam car";
			this.Button19.UseVisualStyleBackColor = false;
			this.Button19.Click += new System.EventHandler(this.SlamCar_Button19_Click);
			this.Label18.AutoSize = true;
			this.Label18.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label18.ForeColor = global::System.Drawing.Color.Red;
			this.Label18.Location = new global::System.Drawing.Point(6, 16);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(111, 13);
			this.Label18.TabIndex = 35;
			this.Label18.Text = "Suspension height";
			this.SuspensionHeightFrontTextBox.Location = new global::System.Drawing.Point(123, 13);
			this.SuspensionHeightFrontTextBox.Name = "TextBox14";
			this.SuspensionHeightFrontTextBox.Size = new global::System.Drawing.Size(42, 20);
			this.SuspensionHeightFrontTextBox.TabIndex = 36;
			this.Label22.AutoSize = true;
			this.Label22.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label22.ForeColor = global::System.Drawing.Color.Red;
			this.Label22.Location = new global::System.Drawing.Point(171, 42);
			this.Label22.Name = "Label22";
			this.Label22.Size = new global::System.Drawing.Size(10, 13);
			this.Label22.TabIndex = 44;
			this.Label22.Text = ":";
			this.SuspensionHeightRearTextBox.Location = new global::System.Drawing.Point(187, 13);
			this.SuspensionHeightRearTextBox.Name = "TextBox15";
			this.SuspensionHeightRearTextBox.Size = new global::System.Drawing.Size(42, 20);
			this.SuspensionHeightRearTextBox.TabIndex = 37;
			this.SpringRateRearTextBox.Location = new global::System.Drawing.Point(187, 39);
			this.SpringRateRearTextBox.Name = "TextBox17";
			this.SpringRateRearTextBox.Size = new global::System.Drawing.Size(42, 20);
			this.SpringRateRearTextBox.TabIndex = 43;
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.ForeColor = global::System.Drawing.Color.Red;
			this.Label19.Location = new global::System.Drawing.Point(171, 16);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(10, 13);
			this.Label19.TabIndex = 38;
			this.Label19.Text = ":";
			this.SpringRateFrontTextBox.Location = new global::System.Drawing.Point(123, 39);
			this.SpringRateFrontTextBox.Name = "TextBox18";
			this.SpringRateFrontTextBox.Size = new global::System.Drawing.Size(42, 20);
			this.SpringRateFrontTextBox.TabIndex = 42;
			this.Label21.AutoSize = true;
			this.Label21.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label21.ForeColor = global::System.Drawing.Color.Red;
			this.Label21.Location = new global::System.Drawing.Point(48, 42);
			this.Label21.Name = "Label21";
			this.Label21.Size = new global::System.Drawing.Size(69, 13);
			this.Label21.TabIndex = 41;
			this.Label21.Text = "Spring rate";
			this.TabControl1.Controls.Add(this.TabPage1);
			this.TabControl1.Controls.Add(this.TabPage4);
			this.TabControl1.Location = new global::System.Drawing.Point(13, 121);
			this.TabControl1.Name = "TabControl1";
			this.TabControl1.SelectedIndex = 0;
			this.TabControl1.Size = new global::System.Drawing.Size(368, 338);
			this.TabControl1.TabIndex = 2;
			this.TabPage1.Controls.Add(this.Label37);
			this.TabPage1.Controls.Add(this.Button12);
			this.TabPage1.Controls.Add(this.Label30);
			this.TabPage1.Controls.Add(this.ComboBox8);
			this.TabPage1.Controls.Add(this.Label29);
			this.TabPage1.Controls.Add(this.ComboBox7);
			this.TabPage1.Controls.Add(this.Label28);
			this.TabPage1.Controls.Add(this.ComboBox6);
			this.TabPage1.Controls.Add(this.Label27);
			this.TabPage1.Controls.Add(this.ComboBox5);
			this.TabPage1.Controls.Add(this.Label26);
			this.TabPage1.Controls.Add(this.ComboBox4);
			this.TabPage1.Controls.Add(this.Label25);
			this.TabPage1.Controls.Add(this.ComboBox3);
			this.TabPage1.Controls.Add(this.Label24);
			this.TabPage1.Controls.Add(this.ComboBox2);
			this.TabPage1.Controls.Add(this.Label23);
			this.TabPage1.Controls.Add(this.ComboBox1);
			global::System.Windows.Forms.TabPage tabPage7 = this.TabPage1;
			tabPage7.Location = new global::System.Drawing.Point(4, 22);
			this.TabPage1.Name = "TabPage1";
			global::System.Windows.Forms.Control tabPage8 = this.TabPage1;
			tabPage8.Padding = new global::System.Windows.Forms.Padding(3);
			global::System.Windows.Forms.Control tabPage9 = this.TabPage1;
			tabPage9.Size = new global::System.Drawing.Size(360, 312);
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "Parts Database";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.Label37.AutoSize = true;
			global::System.Windows.Forms.Control label59 = this.Label37;
			label59.Location = new global::System.Drawing.Point(111, 272);
			this.Label37.Name = "Label37";
			global::System.Windows.Forms.Control label60 = this.Label37;
			label60.Size = new global::System.Drawing.Size(128, 13);
			this.Label37.TabIndex = 17;
			this.Label37.Text = "Look at all this free space";
			this.Button12.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 255);
			this.Button12.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button37 = this.Button12;
			button37.Location = new global::System.Drawing.Point(72, 220);
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control button38 = this.Button12;
			button38.Size = new global::System.Drawing.Size(282, 20);
			this.Button12.TabIndex = 16;
			this.Button12.Text = "Add current car to parts database";
			this.Button12.UseVisualStyleBackColor = false;
			this.Button12.Click += new System.EventHandler(this.Button12_Click);
			this.Label30.AutoSize = true;
			global::System.Windows.Forms.Control label61 = this.Label30;
			label61.Location = new global::System.Drawing.Point(41, 199);
			this.Label30.Name = "Label30";
			global::System.Windows.Forms.Control label62 = this.Label30;
			label62.Size = new global::System.Drawing.Size(30, 13);
			this.Label30.TabIndex = 15;
			this.Label30.Text = "Horn";
			this.ComboBox8.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox8.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox = this.ComboBox8;
			comboBox.Location = new global::System.Drawing.Point(72, 195);
			this.ComboBox8.Name = "ComboBox8";
			global::System.Windows.Forms.Control comboBox2 = this.ComboBox8;
			comboBox2.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox8.Sorted = true;
			this.ComboBox8.TabIndex = 14;
			this.ComboBox8.SelectedIndexChanged += new System.EventHandler(this.ComboBox8_SelectedIndexChanged);
			this.Label29.AutoSize = true;
			global::System.Windows.Forms.Control label63 = this.Label29;
			label63.Location = new global::System.Drawing.Point(43, 171);
			this.Label29.Name = "Label29";
			global::System.Windows.Forms.Control label64 = this.Label29;
			label64.Size = new global::System.Drawing.Size(28, 13);
			this.Label29.TabIndex = 13;
			this.Label29.Text = "LSD";
			this.ComboBox7.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox7.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox3 = this.ComboBox7;
			comboBox3.Location = new global::System.Drawing.Point(72, 168);
			this.ComboBox7.Name = "ComboBox7";
			global::System.Windows.Forms.Control comboBox4 = this.ComboBox7;
			comboBox4.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox7.Sorted = true;
			this.ComboBox7.TabIndex = 12;
			this.ComboBox7.SelectedIndexChanged += new System.EventHandler(this.ComboBox7_SelectedIndexChanged);
			this.Label28.AutoSize = true;
			global::System.Windows.Forms.Control label65 = this.Label28;
			label65.Location = new global::System.Drawing.Point(40, 144);
			this.Label28.Name = "Label28";
			global::System.Windows.Forms.Control label66 = this.Label28;
			label66.Size = new global::System.Drawing.Size(31, 13);
			this.Label28.TabIndex = 11;
			this.Label28.Text = "Body";
			this.ComboBox6.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox6.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox5 = this.ComboBox6;
			comboBox5.Location = new global::System.Drawing.Point(72, 141);
			this.ComboBox6.Name = "ComboBox6";
			global::System.Windows.Forms.Control comboBox6 = this.ComboBox6;
			comboBox6.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox6.Sorted = true;
			this.ComboBox6.TabIndex = 10;
			this.ComboBox6.SelectedIndexChanged += new System.EventHandler(this.ComboBox6_SelectedIndexChanged);
			this.Label27.AutoSize = true;
			global::System.Windows.Forms.Control label67 = this.Label27;
			label67.Location = new global::System.Drawing.Point(9, 117);
			this.Label27.Name = "Label27";
			global::System.Windows.Forms.Control label68 = this.Label27;
			label68.Size = new global::System.Drawing.Size(62, 13);
			this.Label27.TabIndex = 9;
			this.Label27.Text = "Suspension";
			this.ComboBox5.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox5.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox7 = this.ComboBox5;
			comboBox7.Location = new global::System.Drawing.Point(72, 114);
			this.ComboBox5.Name = "ComboBox5";
			global::System.Windows.Forms.Control comboBox8 = this.ComboBox5;
			comboBox8.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox5.Sorted = true;
			this.ComboBox5.TabIndex = 8;
			this.ComboBox5.SelectedIndexChanged += new System.EventHandler(this.ComboBox5_SelectedIndexChanged);
			this.Label26.AutoSize = true;
			global::System.Windows.Forms.Control label69 = this.Label26;
			label69.Location = new global::System.Drawing.Point(3, 90);
			this.Label26.Name = "Label26";
			global::System.Windows.Forms.Control label70 = this.Label26;
			label70.Size = new global::System.Drawing.Size(68, 13);
			this.Label26.TabIndex = 7;
			this.Label26.Text = "Transmission";
			this.ComboBox4.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox4.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox9 = this.ComboBox4;
			comboBox9.Location = new global::System.Drawing.Point(72, 87);
			this.ComboBox4.Name = "ComboBox4";
			global::System.Windows.Forms.Control comboBox10 = this.ComboBox4;
			comboBox10.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox4.Sorted = true;
			this.ComboBox4.TabIndex = 6;
			this.ComboBox4.SelectedIndexChanged += new System.EventHandler(this.ComboBox4_SelectedIndexChanged);
			this.Label25.AutoSize = true;
			global::System.Windows.Forms.Control label71 = this.Label25;
			label71.Location = new global::System.Drawing.Point(28, 63);
			this.Label25.Name = "Label25";
			global::System.Windows.Forms.Control label72 = this.Label25;
			label72.Size = new global::System.Drawing.Size(43, 13);
			this.Label25.TabIndex = 5;
			this.Label25.Text = "Chassis";
			this.ComboBox3.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox3.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox11 = this.ComboBox3;
			comboBox11.Location = new global::System.Drawing.Point(72, 60);
			this.ComboBox3.Name = "ComboBox3";
			global::System.Windows.Forms.Control comboBox12 = this.ComboBox3;
			comboBox12.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox3.Sorted = true;
			this.ComboBox3.TabIndex = 4;
			this.ComboBox3.SelectedIndexChanged += new System.EventHandler(this.ComboBox3_SelectedIndexChanged);
			this.Label24.AutoSize = true;
			global::System.Windows.Forms.Control label73 = this.Label24;
			label73.Location = new global::System.Drawing.Point(19, 36);
			this.Label24.Name = "Label24";
			global::System.Windows.Forms.Control label74 = this.Label24;
			label74.Size = new global::System.Drawing.Size(52, 13);
			this.Label24.TabIndex = 3;
			this.Label24.Text = "Drivetrain";
			this.ComboBox2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox2.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox13 = this.ComboBox2;
			comboBox13.Location = new global::System.Drawing.Point(72, 33);
			this.ComboBox2.Name = "ComboBox2";
			global::System.Windows.Forms.Control comboBox14 = this.ComboBox2;
			comboBox14.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox2.Sorted = true;
			this.ComboBox2.TabIndex = 2;
			this.ComboBox2.SelectedIndexChanged += new System.EventHandler(this.ComboBox2_SelectedIndexChanged);
			this.Label23.AutoSize = true;
			global::System.Windows.Forms.Control label75 = this.Label23;
			label75.Location = new global::System.Drawing.Point(31, 9);
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control label76 = this.Label23;
			label76.Size = new global::System.Drawing.Size(40, 13);
			this.Label23.TabIndex = 1;
			this.Label23.Text = "Engine";
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBox15 = this.ComboBox1;
			comboBox15.Location = new global::System.Drawing.Point(72, 6);
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control comboBox16 = this.ComboBox1;
			comboBox16.Size = new global::System.Drawing.Size(282, 21);
			this.ComboBox1.Sorted = true;
			this.ComboBox1.TabIndex = 0;
			this.ComboBox1.SelectedIndexChanged += new System.EventHandler(this.ComboBox1_SelectedIndexChanged);
			this.TabPage4.Controls.Add(this.Button18);
			this.TabPage4.Controls.Add(this.Button15);
			this.TabPage4.Controls.Add(this.Button13);
			this.TabPage4.Controls.Add(this.Label36);
			this.TabPage4.Location = new global::System.Drawing.Point(4, 22);
			this.TabPage4.Name = "TabPage4";
			this.TabPage4.Padding = new global::System.Windows.Forms.Padding(3);
			this.TabPage4.Size = new global::System.Drawing.Size(360, 312);
			this.TabPage4.TabIndex = 1;
			this.TabPage4.Text = "Misc.";
			this.TabPage4.UseVisualStyleBackColor = true;
			this.Button18.Location = new global::System.Drawing.Point(3, 65);
			this.Button18.Name = "Button18";
			this.Button18.Size = new global::System.Drawing.Size(354, 23);
			this.Button18.TabIndex = 3;
			this.Button18.Text = "Get 4.2 billion credits ($$$)";
			this.Button18.UseVisualStyleBackColor = true;
			this.Button18.Click += new System.EventHandler(this.Button18_Click);
			this.Button15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button15.Location = new global::System.Drawing.Point(3, 31);
			this.Button15.Name = "Button15";
			this.Button15.Size = new global::System.Drawing.Size(354, 28);
			this.Button15.TabIndex = 2;
			this.Button15.Text = "Borrow glitch (Steal car)";
			this.Button15.UseVisualStyleBackColor = true;
			this.Button15.Click += new System.EventHandler(this.Button15_Click);
			this.Button13.BackColor = global::System.Drawing.Color.Red;
			this.Button13.ForeColor = global::System.Drawing.Color.White;
			this.Button13.Location = new global::System.Drawing.Point(174, 2);
			this.Button13.Name = "Button13";
			this.Button13.Size = new global::System.Drawing.Size(75, 23);
			this.Button13.TabIndex = 1;
			this.Button13.Text = "Open";
			this.Button13.UseVisualStyleBackColor = false;
			this.Button13.Click += new System.EventHandler(this.Button13_Click);
			this.Label36.AutoSize = true;
			this.Label36.Location = new global::System.Drawing.Point(6, 7);
			this.Label36.Name = "Label36";
			this.Label36.Size = new global::System.Drawing.Size(162, 13);
			this.Label36.TabIndex = 0;
			this.Label36.Text = "Custom Samba like performance:";
			this.RemoveHoodCheckBox.AutoSize = true;
			this.RemoveHoodCheckBox.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RemoveHoodCheckBox.ForeColor = global::System.Drawing.Color.DarkViolet;
			this.RemoveHoodCheckBox.Location = new global::System.Drawing.Point(6, 37);
			this.RemoveHoodCheckBox.Name = "CheckBox5";
			this.RemoveHoodCheckBox.Size = new global::System.Drawing.Size(104, 17);
			this.RemoveHoodCheckBox.TabIndex = 24;
			this.RemoveHoodCheckBox.Text = "Remove hood";
			this.RemoveHoodCheckBox.UseVisualStyleBackColor = true;
			this.RemoveRearBumperCheckBox.AutoSize = true;
			this.RemoveRearBumperCheckBox.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RemoveRearBumperCheckBox.ForeColor = global::System.Drawing.Color.DarkViolet;
			this.RemoveRearBumperCheckBox.Location = new global::System.Drawing.Point(6, 80);
			this.RemoveRearBumperCheckBox.Name = "CheckBox6";
			this.RemoveRearBumperCheckBox.Size = new global::System.Drawing.Size(143, 17);
			this.RemoveRearBumperCheckBox.TabIndex = 25;
			this.RemoveRearBumperCheckBox.Text = "Remove rear bumper";
			this.RemoveRearBumperCheckBox.UseVisualStyleBackColor = true;
			this.RemoveFrontBumperCheckBox.AutoSize = true;
			this.RemoveFrontBumperCheckBox.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.RemoveFrontBumperCheckBox.ForeColor = global::System.Drawing.Color.DarkViolet;
			this.RemoveFrontBumperCheckBox.Location = new global::System.Drawing.Point(6, 58);
			this.RemoveFrontBumperCheckBox.Name = "CheckBox7";
			this.RemoveFrontBumperCheckBox.Size = new global::System.Drawing.Size(147, 17);
			this.RemoveFrontBumperCheckBox.TabIndex = 26;
			this.RemoveFrontBumperCheckBox.Text = "Remove front bumper";
			this.RemoveFrontBumperCheckBox.UseVisualStyleBackColor = true;
			this.Button23.Location = new global::System.Drawing.Point(150, 36);
			this.Button23.Name = "Button23";
			this.Button23.Size = new global::System.Drawing.Size(26, 61);
			this.Button23.TabIndex = 27;
			this.Button23.Text = "?";
			this.Button23.UseVisualStyleBackColor = true;
			this.Button23.Click += new System.EventHandler(this.Button23_Click);
			this.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new global::System.Drawing.Size(877, 471);
			this.Controls.Add(this.TabControl1);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.MaximizeBox = false;
			this.Name = "Form1";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "GT5 Car hack workshop 2.5 (For GT5 2.14). Created by HeylonNHP";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.TabControl2.ResumeLayout(false);
			this.TabPage2.ResumeLayout(false);
			this.TabPage2.PerformLayout();
			this.GroupBox10.ResumeLayout(false);
			this.GroupBox10.PerformLayout();
			this.GroupBox9.ResumeLayout(false);
			this.GroupBox9.PerformLayout();
			this.GroupBox8.ResumeLayout(false);
			this.GroupBox8.PerformLayout();
			this.GroupBox7.ResumeLayout(false);
			this.GroupBox7.PerformLayout();
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox6.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.TabPage3.ResumeLayout(false);
			this.GroupBox14.ResumeLayout(false);
			this.GroupBox14.PerformLayout();
			this.GroupBox13.ResumeLayout(false);
			this.GroupBox13.PerformLayout();
			this.GroupBox12.ResumeLayout(false);
			this.GroupBox12.PerformLayout();
			this.GroupBox11.ResumeLayout(false);
			this.GroupBox11.PerformLayout();
			this.TabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.TabPage1.PerformLayout();
			this.TabPage4.ResumeLayout(false);
			this.TabPage4.PerformLayout();
			this.ResumeLayout(false);
		}

		private System.Windows.Forms.GroupBox GroupBox1;
		private System.Windows.Forms.Button Button22;
		private System.Windows.Forms.Button Button5;
		private System.Windows.Forms.Label Label2;
		private System.Windows.Forms.TextBox TextBox2;
		private System.Windows.Forms.Button Button3;
		private System.Windows.Forms.Button Button2;
		private System.Windows.Forms.Button Button1;
		private System.Windows.Forms.Label Label1;
		private System.Windows.Forms.TextBox TextBox1;
		private System.Windows.Forms.GroupBox GroupBox2;
		private System.Windows.Forms.TabControl TabControl2;
		private System.Windows.Forms.TabPage TabPage2;
		private System.Windows.Forms.GroupBox GroupBox10;
		private System.Windows.Forms.Label Label4;
		private System.Windows.Forms.TextBox TorqueSplitTextBox;
		private System.Windows.Forms.TextBox TextBox5;
		private System.Windows.Forms.Label Label5;
		private System.Windows.Forms.Button Button8;
		private System.Windows.Forms.GroupBox GroupBox9;
		private System.Windows.Forms.TextBox HornCodeTextBox;
		private System.Windows.Forms.Label Label11;
		private System.Windows.Forms.TextBox TransmissionCodeTextBox;
		private System.Windows.Forms.Label Label10;
		private System.Windows.Forms.Label Label35;
		private System.Windows.Forms.TextBox ChassisCodeTextBox;
		private System.Windows.Forms.Button Button6;
		private System.Windows.Forms.TextBox DrivetrainCodeTextBox;
		private System.Windows.Forms.Label Label6;
		private System.Windows.Forms.TextBox LsdCodeTextBox;
		private System.Windows.Forms.Button Button7;
		private System.Windows.Forms.Button Button4;
		private System.Windows.Forms.Label Label3;
		private System.Windows.Forms.TextBox EngineCodeTextBox;
		private System.Windows.Forms.TextBox CarBodyCodeTextBox;
		private System.Windows.Forms.Label Label33;
		private System.Windows.Forms.Label Label32;
		private System.Windows.Forms.TextBox SuspensionCodeTextBox;
		private System.Windows.Forms.Label Label34;
		private System.Windows.Forms.GroupBox GroupBox8;
		private System.Windows.Forms.Label Label14;
		private System.Windows.Forms.Button Button11;
		private System.Windows.Forms.GroupBox GroupBox7;
		private System.Windows.Forms.TextBox AeroFrontTextBox;
		private System.Windows.Forms.Label Label16;
		private System.Windows.Forms.TextBox AeroRearTextBox;
		private System.Windows.Forms.Label Label17;
		private System.Windows.Forms.GroupBox GroupBox6;
		private System.Windows.Forms.Button Button23;
		private System.Windows.Forms.CheckBox RemoveFrontBumperCheckBox;
		private System.Windows.Forms.CheckBox RemoveRearBumperCheckBox;
		private System.Windows.Forms.CheckBox RemoveHoodCheckBox;
		private System.Windows.Forms.Label Label12;
		private System.Windows.Forms.TextBox RemoveSpoilerCodeTextBox;
		private System.Windows.Forms.Button Button10;
		private System.Windows.Forms.GroupBox GroupBox5;
		private System.Windows.Forms.Button Button17;
		private System.Windows.Forms.Button Button16;
		private System.Windows.Forms.Label Label15;
		public System.Windows.Forms.TextBox TurboModifierTextBox;
		public System.Windows.Forms.TextBox ExhauseMultiplierTextBox;
		private System.Windows.Forms.Label Label31;
		private System.Windows.Forms.CheckBox SambaLikePerformanceCheckbox;
		private System.Windows.Forms.GroupBox GroupBox4;
		private System.Windows.Forms.CheckBox AddLucaBytesCheckBox;
		private System.Windows.Forms.Button Button14;
		private System.Windows.Forms.CheckBox Add74ByteCheckBox;
		private System.Windows.Forms.Button Button9;
		private System.Windows.Forms.GroupBox GroupBox3;
		private System.Windows.Forms.Label Label9;
		private System.Windows.Forms.Label Label8;
		private System.Windows.Forms.Label Label7;
		private System.Windows.Forms.TabPage TabPage3;
		private System.Windows.Forms.GroupBox GroupBox14;
		private System.Windows.Forms.Button Button21;
		private System.Windows.Forms.Button Button20;
		private System.Windows.Forms.Label Label39;
		private System.Windows.Forms.GroupBox GroupBox13;
		private System.Windows.Forms.CheckBox CheckBox4;
		private System.Windows.Forms.TextBox WeightMultiplierTextBox;
		private System.Windows.Forms.Label Label38;
		private System.Windows.Forms.GroupBox GroupBox12;
		private System.Windows.Forms.Label Label13;
		private System.Windows.Forms.TextBox PaintCodesTextBox;
		private System.Windows.Forms.TextBox GripTextBox;
		private System.Windows.Forms.Label Label20;
		private System.Windows.Forms.GroupBox GroupBox11;
		private System.Windows.Forms.Button Button19;
		private System.Windows.Forms.Label Label18;
		private System.Windows.Forms.TextBox SuspensionHeightFrontTextBox;
		private System.Windows.Forms.Label Label22;
		private System.Windows.Forms.TextBox SuspensionHeightRearTextBox;
		private System.Windows.Forms.TextBox SpringRateRearTextBox;
		private System.Windows.Forms.Label Label19;
		private System.Windows.Forms.TextBox SpringRateFrontTextBox;
		private System.Windows.Forms.Label Label21;
		private System.Windows.Forms.TabControl TabControl1;
		private System.Windows.Forms.TabPage TabPage1;
		private System.Windows.Forms.Label Label37;
		private System.Windows.Forms.Button Button12;
		private System.Windows.Forms.Label Label30;
		private System.Windows.Forms.ComboBox ComboBox8;
		private System.Windows.Forms.Label Label29;
		private System.Windows.Forms.ComboBox ComboBox7;
		private System.Windows.Forms.Label Label28;
		private System.Windows.Forms.ComboBox ComboBox6;
		private System.Windows.Forms.Label Label27;
		private System.Windows.Forms.ComboBox ComboBox5;
		private System.Windows.Forms.Label Label26;
		private System.Windows.Forms.ComboBox ComboBox4;
		private System.Windows.Forms.Label Label25;
		private System.Windows.Forms.ComboBox ComboBox3;
		private System.Windows.Forms.Label Label24;
		private System.Windows.Forms.ComboBox ComboBox2;
		private System.Windows.Forms.Label Label23;
		private System.Windows.Forms.ComboBox ComboBox1;
		private System.Windows.Forms.TabPage TabPage4;
		private System.Windows.Forms.Button Button18;
		private System.Windows.Forms.Button Button15;
		private System.Windows.Forms.Button Button13;
		private System.Windows.Forms.Label Label36;

	}
}
