using System.Windows.Forms;

namespace GT5_Car_hack_workshop_2
{
	public partial class TransmissionEditor : global::System.Windows.Forms.Form
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}

			base.Dispose(disposing);
		}
		
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.Label1 = new System.Windows.Forms.Label();
			this.Label2 = new System.Windows.Forms.Label();
			this.Label3 = new System.Windows.Forms.Label();
			this.Label4 = new System.Windows.Forms.Label();
			this.Label5 = new System.Windows.Forms.Label();
			this.Label6 = new System.Windows.Forms.Label();
			this.Label7 = new System.Windows.Forms.Label();
			this.Label8 = new System.Windows.Forms.Label();
			this.Label9 = new System.Windows.Forms.Label();
			this.Label10 = new System.Windows.Forms.Label();
			this.Label11 = new System.Windows.Forms.Label();
			this.TextBox1 = new System.Windows.Forms.TextBox();
			this.TextBox2 = new System.Windows.Forms.TextBox();
			this.TextBox3 = new System.Windows.Forms.TextBox();
			this.TextBox4 = new System.Windows.Forms.TextBox();
			this.TextBox5 = new System.Windows.Forms.TextBox();
			this.TextBox6 = new System.Windows.Forms.TextBox();
			this.TextBox7 = new System.Windows.Forms.TextBox();
			this.TextBox8 = new System.Windows.Forms.TextBox();
			this.TextBox9 = new System.Windows.Forms.TextBox();
			this.TextBox10 = new System.Windows.Forms.TextBox();
			this.TextBox11 = new System.Windows.Forms.TextBox();
			this.TextBox12 = new System.Windows.Forms.TextBox();
			this.Label12 = new System.Windows.Forms.Label();
			this.OkayButton = new System.Windows.Forms.Button();
			this.GroupBox1 = new System.Windows.Forms.GroupBox();
			this.Label13 = new System.Windows.Forms.Label();
			this.TextBox13 = new System.Windows.Forms.TextBox();
			this.Label14 = new System.Windows.Forms.Label();
			this.TextBox14 = new System.Windows.Forms.TextBox();
			this.GroupBox1.SuspendLayout();
			this.SuspendLayout();
			this.Label1.AutoSize = true;
			this.Label1.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label = this.Label1;
			System.Drawing.Point point = new System.Drawing.Point(18, 13);
			label.Location = point;
			this.Label1.Name = "Label1";
			System.Windows.Forms.Control label2 = this.Label1;
			System.Drawing.Size size = new System.Drawing.Size(72, 19);
			label2.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "1st Gear";
			this.Label2.AutoSize = true;
			this.Label2.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label3 = this.Label2;
			point = new System.Drawing.Point(12, 39);
			label3.Location = point;
			this.Label2.Name = "Label2";
			System.Windows.Forms.Control label4 = this.Label2;
			size = new System.Drawing.Size(78, 19);
			label4.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "2nd Gear";
			this.Label3.AutoSize = true;
			this.Label3.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label5 = this.Label3;
			point = new System.Drawing.Point(16, 65);
			label5.Location = point;
			this.Label3.Name = "Label3";
			System.Windows.Forms.Control label6 = this.Label3;
			size = new System.Drawing.Size(74, 19);
			label6.Size = size;
			this.Label3.TabIndex = 2;
			this.Label3.Text = "3rd Gear";
			this.Label4.AutoSize = true;
			this.Label4.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label7 = this.Label4;
			point = new System.Drawing.Point(17, 91);
			label7.Location = point;
			this.Label4.Name = "Label4";
			System.Windows.Forms.Control label8 = this.Label4;
			size = new System.Drawing.Size(73, 19);
			label8.Size = size;
			this.Label4.TabIndex = 3;
			this.Label4.Text = "4th Gear";
			this.Label5.AutoSize = true;
			this.Label5.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label9 = this.Label5;
			point = new System.Drawing.Point(17, 117);
			label9.Location = point;
			this.Label5.Name = "Label5";
			System.Windows.Forms.Control label10 = this.Label5;
			size = new System.Drawing.Size(73, 19);
			label10.Size = size;
			this.Label5.TabIndex = 4;
			this.Label5.Text = "5th Gear";
			this.Label6.AutoSize = true;
			this.Label6.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label11 = this.Label6;
			point = new System.Drawing.Point(17, 143);
			label11.Location = point;
			this.Label6.Name = "Label6";
			System.Windows.Forms.Control label12 = this.Label6;
			size = new System.Drawing.Size(73, 19);
			label12.Size = size;
			this.Label6.TabIndex = 5;
			this.Label6.Text = "6th Gear";
			this.Label7.AutoSize = true;
			this.Label7.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label13 = this.Label7;
			point = new System.Drawing.Point(17, 169);
			label13.Location = point;
			this.Label7.Name = "Label7";
			System.Windows.Forms.Control label14 = this.Label7;
			size = new System.Drawing.Size(73, 19);
			label14.Size = size;
			this.Label7.TabIndex = 6;
			this.Label7.Text = "7th Gear";
			this.Label8.AutoSize = true;
			this.Label8.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label15 = this.Label8;
			point = new System.Drawing.Point(17, 195);
			label15.Location = point;
			this.Label8.Name = "Label8";
			System.Windows.Forms.Control label16 = this.Label8;
			size = new System.Drawing.Size(73, 19);
			label16.Size = size;
			this.Label8.TabIndex = 7;
			this.Label8.Text = "8th Gear";
			this.Label9.AutoSize = true;
			this.Label9.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label17 = this.Label9;
			point = new System.Drawing.Point(17, 221);
			label17.Location = point;
			this.Label9.Name = "Label9";
			System.Windows.Forms.Control label18 = this.Label9;
			size = new System.Drawing.Size(73, 19);
			label18.Size = size;
			this.Label9.TabIndex = 8;
			this.Label9.Text = "9th Gear";
			this.Label10.AutoSize = true;
			this.Label10.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label19 = this.Label10;
			point = new System.Drawing.Point(8, 247);
			label19.Location = point;
			this.Label10.Name = "Label10";
			System.Windows.Forms.Control label20 = this.Label10;
			size = new System.Drawing.Size(82, 19);
			label20.Size = size;
			this.Label10.TabIndex = 9;
			this.Label10.Text = "10th Gear";
			this.Label11.AutoSize = true;
			this.Label11.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label21 = this.Label11;
			point = new System.Drawing.Point(9, 273);
			label21.Location = point;
			this.Label11.Name = "Label11";
			System.Windows.Forms.Control label22 = this.Label11;
			size = new System.Drawing.Size(81, 19);
			label22.Size = size;
			this.Label11.TabIndex = 10;
			this.Label11.Text = "11th Gear";
			this.TextBox1.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox1.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox1.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox = this.TextBox1;
			point = new System.Drawing.Point(96, 14);
			textBox.Location = point;
			this.TextBox1.Name = "TextBox1";
			System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new System.Drawing.Size(104, 20);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 11;
			this.TextBox2.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox2.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox2.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox3 = this.TextBox2;
			point = new System.Drawing.Point(96, 40);
			textBox3.Location = point;
			this.TextBox2.Name = "TextBox2";
			System.Windows.Forms.Control textBox4 = this.TextBox2;
			size = new System.Drawing.Size(104, 20);
			textBox4.Size = size;
			this.TextBox2.TabIndex = 12;
			this.TextBox3.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox3.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox3.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox5 = this.TextBox3;
			point = new System.Drawing.Point(96, 66);
			textBox5.Location = point;
			this.TextBox3.Name = "TextBox3";
			System.Windows.Forms.Control textBox6 = this.TextBox3;
			size = new System.Drawing.Size(104, 20);
			textBox6.Size = size;
			this.TextBox3.TabIndex = 13;
			this.TextBox4.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox4.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox4.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox7 = this.TextBox4;
			point = new System.Drawing.Point(96, 92);
			textBox7.Location = point;
			this.TextBox4.Name = "TextBox4";
			System.Windows.Forms.Control textBox8 = this.TextBox4;
			size = new System.Drawing.Size(104, 20);
			textBox8.Size = size;
			this.TextBox4.TabIndex = 14;
			this.TextBox5.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox5.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox5.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox9 = this.TextBox5;
			point = new System.Drawing.Point(96, 118);
			textBox9.Location = point;
			this.TextBox5.Name = "TextBox5";
			System.Windows.Forms.Control textBox10 = this.TextBox5;
			size = new System.Drawing.Size(104, 20);
			textBox10.Size = size;
			this.TextBox5.TabIndex = 15;
			this.TextBox6.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox6.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox6.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox11 = this.TextBox6;
			point = new System.Drawing.Point(96, 144);
			textBox11.Location = point;
			this.TextBox6.Name = "TextBox6";
			System.Windows.Forms.Control textBox12 = this.TextBox6;
			size = new System.Drawing.Size(104, 20);
			textBox12.Size = size;
			this.TextBox6.TabIndex = 16;
			this.TextBox7.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox7.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox7.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox13 = this.TextBox7;
			point = new System.Drawing.Point(96, 170);
			textBox13.Location = point;
			this.TextBox7.Name = "TextBox7";
			System.Windows.Forms.Control textBox14 = this.TextBox7;
			size = new System.Drawing.Size(104, 20);
			textBox14.Size = size;
			this.TextBox7.TabIndex = 17;
			this.TextBox8.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox8.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox8.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox15 = this.TextBox8;
			point = new System.Drawing.Point(96, 196);
			textBox15.Location = point;
			this.TextBox8.Name = "TextBox8";
			System.Windows.Forms.Control textBox16 = this.TextBox8;
			size = new System.Drawing.Size(104, 20);
			textBox16.Size = size;
			this.TextBox8.TabIndex = 18;
			this.TextBox9.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox9.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox9.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox17 = this.TextBox9;
			point = new System.Drawing.Point(96, 222);
			textBox17.Location = point;
			this.TextBox9.Name = "TextBox9";
			System.Windows.Forms.Control textBox18 = this.TextBox9;
			size = new System.Drawing.Size(104, 20);
			textBox18.Size = size;
			this.TextBox9.TabIndex = 19;
			this.TextBox10.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox10.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox10.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox19 = this.TextBox10;
			point = new System.Drawing.Point(96, 248);
			textBox19.Location = point;
			this.TextBox10.Name = "TextBox10";
			System.Windows.Forms.Control textBox20 = this.TextBox10;
			size = new System.Drawing.Size(104, 20);
			textBox20.Size = size;
			this.TextBox10.TabIndex = 20;
			this.TextBox11.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox11.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox11.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox21 = this.TextBox11;
			point = new System.Drawing.Point(96, 274);
			textBox21.Location = point;
			this.TextBox11.Name = "TextBox11";
			System.Windows.Forms.Control textBox22 = this.TextBox11;
			size = new System.Drawing.Size(104, 20);
			textBox22.Size = size;
			this.TextBox11.TabIndex = 21;
			this.TextBox12.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox12.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox12.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox23 = this.TextBox12;
			point = new System.Drawing.Point(96, 300);
			textBox23.Location = point;
			this.TextBox12.Name = "TextBox12";
			System.Windows.Forms.Control textBox24 = this.TextBox12;
			size = new System.Drawing.Size(104, 20);
			textBox24.Size = size;
			this.TextBox12.TabIndex = 22;
			this.Label12.AutoSize = true;
			this.Label12.Font = new System.Drawing.Font("Arial", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label23 = this.Label12;
			point = new System.Drawing.Point(4, 299);
			label23.Location = point;
			this.Label12.Name = "Label12";
			System.Windows.Forms.Control label24 = this.Label12;
			size = new System.Drawing.Size(86, 19);
			label24.Size = size;
			this.Label12.TabIndex = 23;
			this.Label12.Text = "Final Gear";
			this.OkayButton.BackColor = System.Drawing.Color.FromArgb(192, 255, 255);
			System.Windows.Forms.Control button = this.OkayButton;
			point = new System.Drawing.Point(1, 327);
			button.Location = point;
			this.OkayButton.Name = "OkayButton";
			System.Windows.Forms.Control button2 = this.OkayButton;
			size = new System.Drawing.Size(210, 26);
			button2.Size = size;
			this.OkayButton.TabIndex = 24;
			this.OkayButton.Text = "Okay";
			this.OkayButton.UseVisualStyleBackColor = false;
			this.OkayButton.Click += new System.EventHandler(this.OkayButtonClick);
			this.GroupBox1.Controls.Add(this.TextBox14);
			this.GroupBox1.Controls.Add(this.Label14);
			this.GroupBox1.Controls.Add(this.TextBox13);
			this.GroupBox1.Controls.Add(this.Label13);
			System.Windows.Forms.Control groupBox = this.GroupBox1;
			point = new System.Drawing.Point(217, 12);
			groupBox.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new System.Drawing.Size(136, 330);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 25;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Calculate speed";
			this.Label13.AutoSize = true;
			this.Label13.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label25 = this.Label13;
			point = new System.Drawing.Point(7, 20);
			label25.Location = point;
			this.Label13.Name = "Label13";
			System.Windows.Forms.Control label26 = this.Label13;
			size = new System.Drawing.Size(96, 13);
			label26.Size = size;
			this.Label13.TabIndex = 0;
			this.Label13.Text = "Original max speed";
			this.TextBox13.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox13.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox13.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox25 = this.TextBox13;
			point = new System.Drawing.Point(6, 36);
			textBox25.Location = point;
			this.TextBox13.Name = "TextBox13";
			System.Windows.Forms.Control textBox26 = this.TextBox13;
			size = new System.Drawing.Size(124, 20);
			textBox26.Size = size;
			this.TextBox13.TabIndex = 26;
			this.TextBox13.Text = "0";
			this.Label14.AutoSize = true;
			this.Label14.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control label27 = this.Label14;
			point = new System.Drawing.Point(7, 59);
			label27.Location = point;
			this.Label14.Name = "Label14";
			System.Windows.Forms.Control label28 = this.Label14;
			size = new System.Drawing.Size(95, 13);
			label28.Size = size;
			this.Label14.TabIndex = 27;
			this.Label14.Text = "Current max speed";
			this.TextBox14.BackColor = System.Drawing.Color.FromArgb(0, 64, 64);
			this.TextBox14.Font = new System.Drawing.Font("Arial", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
			this.TextBox14.ForeColor = System.Drawing.Color.FromArgb(128, 255, 255);
			System.Windows.Forms.Control textBox27 = this.TextBox14;
			point = new System.Drawing.Point(6, 75);
			textBox27.Location = point;
			this.TextBox14.Name = "TextBox14";
			System.Windows.Forms.Control textBox28 = this.TextBox14;
			size = new System.Drawing.Size(124, 20);
			textBox28.Size = size;
			this.TextBox14.TabIndex = 28;
			this.TextBox14.Text = "???";
			System.Drawing.SizeF sizeF = new System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.Color.Gray;
			size = new System.Drawing.Size(365, 354);
			this.ClientSize = size;
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.OkayButton);
			this.Controls.Add(this.Label12);
			this.Controls.Add(this.TextBox12);
			this.Controls.Add(this.TextBox11);
			this.Controls.Add(this.TextBox10);
			this.Controls.Add(this.TextBox9);
			this.Controls.Add(this.TextBox8);
			this.Controls.Add(this.TextBox7);
			this.Controls.Add(this.TextBox6);
			this.Controls.Add(this.TextBox5);
			this.Controls.Add(this.TextBox4);
			this.Controls.Add(this.TextBox3);
			this.Controls.Add(this.TextBox2);
			this.Controls.Add(this.TextBox1);
			this.Controls.Add(this.Label11);
			this.Controls.Add(this.Label10);
			this.Controls.Add(this.Label9);
			this.Controls.Add(this.Label8);
			this.Controls.Add(this.Label7);
			this.Controls.Add(this.Label6);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.Label1);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "TransmissionEditor";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Transmission editor";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		
		private System.Windows.Forms.Button OkayButton;
		
		private System.Windows.Forms.Label Label1;
		private System.Windows.Forms.Label Label2;
		private System.Windows.Forms.Label Label3;
		private System.Windows.Forms.Label Label4;
		private System.Windows.Forms.Label Label5;
		private System.Windows.Forms.Label Label6;
		private System.Windows.Forms.Label Label7;
		private System.Windows.Forms.Label Label8;
		private System.Windows.Forms.Label Label9;
		private System.Windows.Forms.Label Label10;
		private System.Windows.Forms.Label Label11;
		private System.Windows.Forms.Label Label12;
		private System.Windows.Forms.Label Label13;
		private System.Windows.Forms.Label Label14;
		
		private System.Windows.Forms.TextBox TextBox1;
		private System.Windows.Forms.TextBox TextBox2;
		private System.Windows.Forms.TextBox TextBox3;
		private System.Windows.Forms.TextBox TextBox4;
		private System.Windows.Forms.TextBox TextBox5;
		private System.Windows.Forms.TextBox TextBox6;
		private System.Windows.Forms.TextBox TextBox7;
		private System.Windows.Forms.TextBox TextBox8;
		private System.Windows.Forms.TextBox TextBox9;
		private System.Windows.Forms.TextBox TextBox10;
		private System.Windows.Forms.TextBox TextBox11;
		private System.Windows.Forms.TextBox TextBox12;
		private System.Windows.Forms.TextBox TextBox13;
		private System.Windows.Forms.TextBox TextBox14;
		
		private System.Windows.Forms.GroupBox GroupBox1;
	}
}
